nventive/UnoApplicationTemplate

src/app/ApplicationTemplate.Droid/ApplicationTemplate.Droid.csproj, src/app/ApplicationTemplate.Shared/Presentation/ChuckNorris/ChuckNorrisFavoritesPageViewModel.cs, src/app/ApplicationTemplate.Tests/ApplicationTemplate.Tests.csproj, src/app/ApplicationTemplate.UWP/ApplicationTemplate.UWP.csproj, src/app/ApplicationTemplate.UWP/Views/Shell.xaml, src/app/ApplicationTemplate.iOS/ApplicationTemplate.iOS.csproj
- Feature
- Update DataLoader to benefit from SubscribeToData and DisposeWithNextLoad.
- Use `UpdateOnCollectionChanged` in `ChuckNorrisFavoritesPageViewModel` to automatically show the empty state when removing all favorites.
- Use `DisposeWithNextLoad` on the observable list subscription in `ChuckNorrisFavoritesPageViewModel.LoadQuotes`.
=> Update DataLoader to benefit from SubscribeToData and DisposeWithNextLoad.

src/app/ApplicationTemplate.Shared/Presentation/Diagnostics/DiagnosticsOverlayViewModel.cs, src/app/ApplicationTemplate.UWP/Views/Content/Diagnostics/DiagnosticsOverlay.xaml, src/app/ApplicationTemplate.UWP/Views/Shell.xaml
- Feature
I've added a more button on the diagnostic overlay. This basically expand the diagnostic horizontally and vertically.
N/A
=> Add more button on diagnostic overlay

src/app/ApplicationTemplate.Shared/CoreStartup.cs
- Bugfix
Surround #if statements with //-:cnd:noEmit and //-:cnd:noEmit.
This is related to [this comment](https://github.com/nventive/UnoApplicationTemplate/pull/14/files#r485917577).
=> Fix corestartup with //-:cnd:noEmit

src/app/ApplicationTemplate.UWP/Views/Styles/Controls/CommandBar.xaml
- Bugfix
-  iOS NavigationBar height is 44 and this should not be changed. When we set anything higher than that to a CommandBar we are "overflowing" the space iOS allows, causing the display of the command bar to be wrong.
=> fix: removed height setter on the NativeCommandBarPresenter

CHANGELOG.md, build/stage-release-appcenter.yml, build/stage-release-appstore.yml, build/stage-release-googleplay.yml, build/stage-release-wasm.yml, build/steps-build-wasm.yml, doc/BuildPipeline.md
Adds more cleanup steps to the pipeline. The release stages are now deleting the downloaded artifacts once they have been processed.
=> ci: adds cleanup steps for the release stages

src/app/ApplicationTemplate.iOS/ApplicationTemplate.iOS.csproj
Fix output error with vs 16.9.0+ for IOS :
error CS1705: Assembly 'System.Text.Json' with identity 'System.Text.Json, Version=4.0.1.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51' uses 'System.Memory, Version=4.0.1.1, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51' which has a higher version than referenced assembly 'System.Memory' with identity 'System.Memory, Version=4.0.1.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'
- Bugfix
=> Update System.Memory dependency to build on IOS vs VS 16.9.0+

build/stage-release-appcenter.yml, build/stage-release-appstore.yml, build/stage-release-googleplay.yml, build/stage-release-wasm.yml
This PR fixes the cleanup process after the release. The process currently tries to delete both the downloaded artifact and the source code folder if any, with the latter usually failing. The process has been adjusted to make sure only the downloaded artifact is being removed after the release.
=> ci: Improves artifact cleanup

gitversion.yml
- Feature
- Add support for "main" branch as the new "master". It's the new default in AzureDevops repositories.
- This new version supports both "master" and "main".
=> feat(gitversion): Add support for main branch

build/stage-release-appcenter.yml, build/steps-build.yml
Adds the release notes generation step. This generates a simple markdown file with information about the commit, the branch, the build pipeline and the application environment.
This PR also includes a fix for the AppCenter release for Android.
=> ci: adds release notes generation

build/steps-build.yml, build/variables.yml
**Bugfix** : 
- Fixing `ApplicationBundleIdentifier` , `BundleShortVersion`, `BundleVersion `not being replaced correctly in `Info.Plist` for iOS (the production stage is always failing due to this) 
- Fixing `BuildNumber` for Android always one step ahead of what's expected (it falls back to git count instead of relying on semver) 
Use specific tasks to replace `BundleIdentifier` and `Versions `, so the production stage stops failing. 
Use `ApplicationBuildNumber `msbuild argument to correctly set Build version for Android 
=> ci : fix bundleidentifier and version replace fail for iOS - Android fix build number

.azure-pipelines-canary.yml, .azure-pipelines.yml, build/canary-merge.yml, build/stage-build.yml, build/stage-release-appcenter.yml, build/stage-release-appstore.yml, build/stage-release-googleplay.yml, build/steps-build-release-notes.yml, build/steps-build.yml, build/variables.yml
- Update yml structure.
- Remove canary build from regular pipeline.
- Create separate yml for the canary pipeline.
=> chore: Split canary and regular pipeline into 2

.azure-pipelines.yml, .template.config/template.json, build/stage-build.yml, build/stage-donetnew.yaml, build/steps-build.yml
Add automatic CI validation to test the dotnet templating feature.
- Add stage to run `dotnet new nv-mobile -n GeneratedApp`
- Add stage to build the resulting GeneratedApp in Staging.
=> feat: Add dotnet new CI validation

build/stage-release-appcenter.yml
- `AppCenter `now supports pushing aab directly. 
- Removed `BundleTool` task to extract apk from aab as we don't need it anymore.
=> ci: pass in aab directly to appcenter task

src/app/ApplicationTemplate.UWP/App.xaml, src/app/ApplicationTemplate.UWP/ApplicationTemplate.UWP.csproj, src/app/ApplicationTemplate.UWP/Views/Styles/Controls/CommandBar.xaml, src/app/ApplicationTemplate.UWP/Views/Styles/Controls/Frame.xaml
- Bugfix
added native style for frame
###Before
###After
[ALL] Inconsistent Command Bar Behavior
https://dev.azure.com/nventive/Practice%20committees/_boards/board/t/Mobile%20(.Net)/Features/?workitem=256029
=> fix: 256029 [ALL] Inconsistent Command Bar Behavior

src/app/ApplicationTemplate.UWP/Views/Content/Authentication/ResetPasswordPage.xaml
- Feature
General clean up of the xaml file that include stuff like: 
Clean up ResetPasswordPage.xaml
[TODO](https://dev.azure.com/nventive/Practice%20committees/_workitems/edit/259217)
=> feat: Clean up ResetPasswordPage.xaml

src/app/ApplicationTemplate.UWP/Views/Content/Settings/SettingsPage.xaml, src/app/ApplicationTemplate.UWP/Views/Styles/Application/Brushes.xaml
- Feature
Clean up SettingsPage.xaml
https://dev.azure.com/nventive/Practice%20committees/_workitems/edit/259233
=> feat: Clean up SettingsPage.xaml

src/app/ApplicationTemplate.UWP/Views/Content/Diagnostics/DiagnosticsPage.xaml, src/app/ApplicationTemplate.UWP/Views/Content/Welcome/OnboardingPage.xaml, src/app/ApplicationTemplate.UWP/Views/Styles/Application/Brushes.xaml
- Feature
Reorganize the order of properties in control in a more logical manner
Remove unnecessary blend using
Ensure proper use of material color resources
Reorganization of layout (like using stack panels instead of manually defines rows)
Clean up DiagnosticsPage.xaml
https://dev.azure.com/nventive/Practice%20committees/_workitems/edit/259227
=> feat: Clean up DiagnosticsPage.xaml

src/app/ApplicationTemplate.UWP/Views/Content/Posts/EditPostPage.xaml, src/app/ApplicationTemplate.UWP/Views/Styles/Controls/CommandBar.xaml
- Feature
Reorganize the order of properties in control in a more logical manner
Remove unnecessary blend using
Ensure proper use of material color resources
Reorganization of layout (like using stack panels instead of manually defines rows)
Clean up EditPostPage.xaml
https://dev.azure.com/nventive/Practice%20committees/_workitems/edit/259230
=> feat: Clean up EditPostPage.xaml

.azure-pipelines-canary.yml
updated canary xaml to point to the correct andriod/iOSVariableGroup
=> fix: android and ios variable group now correct

src/app/ApplicationTemplate.Presentation/ViewModels/Diagnostics/DiagnosticsViewModelExtensions.cs, src/app/ApplicationTemplate.Presentation/ViewModels/Diagnostics/HttpDebugger/HttpDebuggerViewModel.cs, src/app/ApplicationTemplate.Presentation/ViewModels/Diagnostics/SettingsDiagnosticsViewModel.cs, src/app/ApplicationTemplate.Shared.Views/Content/Diagnostics/HttpDebuggerView.xaml
- Feature
- Add a button to enable or disable the HttpDebugger.
=> Allow the usage of HttpDebugger in release

src/app/ApplicationTemplate.Client/Framework/HttpDebugger/HttpDebuggerHandler.cs, src/app/ApplicationTemplate.Client/Framework/HttpDebugger/HttpTrace.cs, src/app/ApplicationTemplate.Presentation/Configuration/ViewModelConfiguration.cs, src/app/ApplicationTemplate.Presentation/Framework/DataLoader/LogErrorDataLoaderStrategy.cs, src/app/ApplicationTemplate.Presentation/ViewModels/Diagnostics/HttpDebugger/HttpDebuggerViewModel.cs, src/app/ApplicationTemplate.Shared.Views/Configuration/LoggingConfiguration.cs
- Feature
- Enable Android console log colorization in Visual Studio in debug.
- Log errors from DataLoaders.
- Show exception of failed HTTP requests in HttpDebuggerView.
=> feat: Improve logging by showing more exceptions

src/app/ApplicationTemplate.Shared.Views/Content/Diagnostics/DiagnosticsPage.xaml, src/app/ApplicationTemplate.Shared.Views/Content/Settings/SettingsPage.xaml, src/app/ApplicationTemplate.Shared.Views/Styles/Application/Brushes.xaml, src/app/ApplicationTemplate.Shared.Views/Styles/Application/ColorPalette.xaml, src/app/ApplicationTemplate.Shared.Views/Styles/Application/MaterialOverride.xaml, src/app/ApplicationTemplate.Shared.Views/Styles/Controls/PathControl.xaml
- Bugfix
- Move non-material colors to ColorPalette.xaml.
- Use correct name for light and dark variants of Material primary and secondary.
- Remove the word "Material" from non-Material resources.
=> fix: Improve Uno.Material usage

src/app/ApplicationTemplate.Mobile/ApplicationTemplate.Mobile.csproj, src/app/ApplicationTemplate.Presentation/ApplicationTemplate.Presentation.csproj, src/app/ApplicationTemplate.Presentation/ViewModels/DadJokes/DadJokesPageViewModel.cs, src/app/ApplicationTemplate.Presentation/ViewModels/Posts/PostsPageViewModel.cs, src/app/ApplicationTemplate.Shared.Views/Content/DadJokes/DadJokesPage.xaml, src/app/ApplicationTemplate.Shared.Views/Content/Posts/PostsPage.xaml, src/app/ApplicationTemplate.Shared.Views/Startup.cs, src/app/ApplicationTemplate.Windows/ApplicationTemplate.Windows.csproj
- Feature
- Update the Chinook.DataLoader packages to leverage `DataLoaderView.DefaultRefreshCommandProvider`.
- This allows to configure a default refresh command that applies to any `DataLoaderView`.
- This allows to reduce the code in ViewModels that use IDataLoader because they no longer need to create a RefreshCommand per DataLoader.
=> feat: Leverage `DataLoaderView.DefaultRefreshCommandProvider`

src/app/ApplicationTemplate.Mobile/Android/MainActivity.Android.cs, src/app/ApplicationTemplate.Mobile/ApplicationTemplate.Mobile.csproj, src/app/ApplicationTemplate.Windows/ApplicationTemplate.Windows.csproj
- Bugfix
Update ExtendedSplashScreen packages to support the Android 12+ visuals.
In the following videos, the ExtendedSplashScreen is when we see a loading wheel.
https://user-images.githubusercontent.com/39710855/221656890-82cd638b-af33-4716-be59-4d627be7ec2e.mp4
https://user-images.githubusercontent.com/39710855/221656902-32b45c45-524e-447c-9120-0c677914a8ed.mp4
=> fix: Use proper visual for Android 12+ extended splash screen.

src/app/ApplicationTemplate.Presentation/Framework/ViewModels/IViewModel.Extensions.Deactivation.cs, src/app/ApplicationTemplate.Presentation/Framework/ViewModels/TabViewModel.cs, src/app/ApplicationTemplate.Presentation/ViewModels/Diagnostics/DiagnosticsOverlayViewModel.cs, src/app/ApplicationTemplate.Presentation/ViewModels/Diagnostics/HttpDebugger/HttpDebuggerViewModel.cs, src/app/ApplicationTemplate.Presentation/ViewModels/Diagnostics/HttpDebugger/HttpTraceItemViewModel.cs, src/app/ApplicationTemplate.Presentation/ViewModels/Diagnostics/Navigation/NavigationDebuggerViewModel.cs, src/app/ApplicationTemplate.Shared.Views/ApplicationTemplate.Shared.Views.projitems, src/app/ApplicationTemplate.Shared.Views/Content/Diagnostics/DiagnosticsOverlay.xaml, src/app/ApplicationTemplate.Shared.Views/Content/Diagnostics/DiagnosticsTabPresenter.cs, src/app/ApplicationTemplate.Shared.Views/Content/Diagnostics/HttpDebuggerView.xaml.cs
- Feature
- Add tabs to the expanded DiagnosticsOverlay.
There's currently 2 tabs: HTTP (`HttpDebuggerView`) and Navigation (empty for now).
=> feat: Add tabs to the expanded DiagnosticsOverlay.

src/app/ApplicationTemplate.Shared.Views/Framework/Connectivity/ConnectivityProvider.cs
- Bugfix
Made it so that if you unsuscribe to the connectivity event, the service will not unsuscribe from the NetworkStatusChanged Event unless there are no other subscription to the connectivity event.
=> fix: Connectivity provider

src/app/ApplicationTemplate.Presentation/ViewModels/Diagnostics/DiagnosticsOverlayViewModel.cs, src/app/ApplicationTemplate.Shared.Views/Content/Diagnostics/DiagnosticsOverlay.xaml, src/app/ApplicationTemplate.Shared.Views/Shell.xaml
- Feature
I've added a button to temporarily close the diagnostic overlay so it be hidden especially when developing especially on stuff that can be hidden by the overlay.
=> feat: add a close button on diagnostic overlay

src/app/ApplicationTemplate.Shared.Views/Behaviors/FormattingTextBoxBehavior.cs, src/app/ApplicationTemplate.Shared.Views/Behaviors/FormattingTextBoxBehavior.iOS.cs, src/app/ApplicationTemplate.Shared.Views/Content/Settings/SettingsPage.xaml
- Bugfix
fix app crash when focus (iOS) or type (on Windows) in Postal Code and Phone Number fields
[Bug 283022](https://dev.azure.com/nventive/Practice%20committees/_workitems/edit/283022): App crash on Create Account page when some fields get focused
=> fix(283022): fix app crash when focus or type in some fields

src/app/ApplicationTemplate.Presentation/ViewModels/Diagnostics/SummaryDiagnosticsViewModel.cs
related to https://github.com/unoplatform/uno/discussions/10985
- Feature
Decode OS version for diagnostic.
When using DeviceFamilyVersion, we receive 4503616807370751 for iOS version, the decoding gives 16.4.1
=> feat: decode OS version for diagnostic

src/app/ApplicationTemplate.Presentation/Configuration/ConfigurationConfiguration.cs, src/app/ApplicationTemplate.Presentation/Configuration/ReadOnlyConfigurationOptions.cs, src/app/ApplicationTemplate.Presentation/Framework/Diagnostics/IDiagnosticsService.cs, src/app/ApplicationTemplate.Presentation/ViewModels/Diagnostics/Configuration/ConfigurationDebuggerViewModel.cs, src/app/ApplicationTemplate.Shared.Views/Content/Diagnostics/ConfigurationDebuggerView.xaml, src/app/ApplicationTemplate.Shared.Views/Framework/DiagnosticsService.cs
- Feature
- Add button to delete the configuration override file (appsettings.override.json) from the Configuration tab of the expanded diagnostics overlay.
https://github.com/nventive/UnoApplicationTemplate/assets/39710855/50256ee0-03c0-45c9-8027-646bf4a1c75c
=> feat: Add button to delete configuration override file

src/app/ApplicationTemplate.Shared.Views/Styles/Controls/CommandBar.xaml
- Bugfix
This PR fixes the bug on iOS where the screen reader would read the title in the command bar twice.
=> fix(281263): screen reader support for command bar

src/app/ApplicationTemplate.Presentation/ViewModels/Diagnostics/Configuration/ConfigurationDebuggerViewModel.cs, src/app/ApplicationTemplate.Shared.Views/Content/Diagnostics/ConfigurationDebuggerView.xaml
- Feature
Add ComboBox in the ConfigurationDebuggerView to quickly pick a configuration key in the editor.
=> feat: Add picker for configuration keys.

src/app/ApplicationTemplate.Presentation/Configuration/DiagnosticsConfiguration.cs, src/app/ApplicationTemplate.Presentation/ViewModels/Diagnostics/DiagnosticsOverlayViewModel.cs, src/app/ApplicationTemplate.Shared.Views/Content/Diagnostics/DiagnosticsOverlay.xaml
- Feature
Add option to move the diagnostics overlay left and right.
This is useful when the overlay is obscuring important parts of the UI.
=> feat: Add options to move the diagnostics overlay left and right.

.template.config/build/gitversion-config.yml, .template.config/build/stage-publish-template.yml, build/templates/gitversion.yml
- Bugfix
Add `stable` tag to informational versions of builds from the main branch to prevent a build issue on Android and iOS.
=> fix: Add stable tag to versions from main to prevent build issue.

CHANGELOG.md, src/app/ApplicationTemplate.Shared.Views/Configuration/LocalizationConfiguration.cs
* Fixed WinUI app always being in French. …
=> fix: ThreadCultureOverrideService now properly sets the language of the WinUI app.

CHANGELOG.md, src/app/ApplicationTemplate.Mobile/ApplicationTemplate.Mobile.csproj
Fix crash on ARM base Mac when launching iOS simulator.
Set `ForceSimulatorX64ArchitectureInIDE` to fix clang++ error for net7.0-ios. [see this issue](https://github.com/dotnet/maui/issues/16778#issuecomment-1683343255)
- Update …
=> fix: M1 mac crash on simulator

.azure-pipelines-canary.yml, CHANGELOG.md, build/canary-merge.yml
fix: switch canary agents to hosted agents …
=> fix: switch canary agents to hosted agents

.azure-pipelines-api-integration-tests.yml, CHANGELOG.md
I've made sure that the Api Integration pipeline is not triggered after a commit for any branch.
- Update `Diagnostics.md` if you made changes to …
=> fix: remove all triggers on the api integration test pipeline

CHANGELOG.md, src/app/ApplicationTemplate.Shared.Views/Content/Diagnostics/ConfigurationDebuggerView.xaml, src/app/ApplicationTemplate.Shared.Views/Content/Diagnostics/HttpDebuggerView.xaml
- Remove usage of deprecated Material V1 resources in diagnostics which caused crashes on WinUI.
- Update `Diagnostics.md` if you made changes to …
=> fix: Remove usage of deprecated Material V1 resources in diagnostics styles

CHANGELOG.md, src/app/ApplicationTemplate.Mobile/ApplicationTemplate.Mobile.csproj, src/app/ApplicationTemplate.Presentation/ApplicationTemplate.Presentation.csproj, src/app/ApplicationTemplate.Shared.Views/Startup.cs, src/app/ApplicationTemplate.Windows/ApplicationTemplate.Windows.csproj
- Add support for mouse back button navigation.
- Update `Architecture.md` and …
=> feat: Add support for mouse back button navigation.

CHANGELOG.md, README.md, doc/Architecture.md, doc/ForcedUpdate.md, src/app/ApplicationTemplate.Access/ApiClients/MinimumVersion/IMinimumVersionReposiory.cs, src/app/ApplicationTemplate.Access/ApiClients/MinimumVersion/MinimumVersionRepositoryMock.cs, src/app/ApplicationTemplate.Access/Configuration/ApplicationStoreUrisOptions.cs, src/app/ApplicationTemplate.Business/ForcedUpdates/IUpdateRequiredService.cs, src/app/ApplicationTemplate.Business/ForcedUpdates/UpdateRequiredService.cs, src/app/ApplicationTemplate.Presentation/Configuration/ApiConfiguration.cs, src/app/ApplicationTemplate.Presentation/Configuration/AppServicesConfiguration.cs, src/app/ApplicationTemplate.Presentation/CoreStartup.cs, src/app/ApplicationTemplate.Presentation/Framework/Launcher/IAppStoreUriProvider.cs, src/app/ApplicationTemplate.Presentation/ViewModels/Diagnostics/Navigation/NavigationDebuggerViewModel.cs, src/app/ApplicationTemplate.Presentation/ViewModels/ForcedUpdatePageViewModel.cs, src/app/ApplicationTemplate.Presentation/appsettings.json, src/app/ApplicationTemplate.Shared.Views/ApplicationTemplate.Shared.Views.projitems, src/app/ApplicationTemplate.Shared.Views/Configuration/NavigationConfiguration.cs, src/app/ApplicationTemplate.Shared.Views/Configuration/ViewServicesConfiguration.cs, src/app/ApplicationTemplate.Shared.Views/Content/Diagnostics/NavigationDebuggerView.xaml, src/app/ApplicationTemplate.Shared.Views/Content/ForcedUpdate/ForcedUpdatePage.xaml, src/app/ApplicationTemplate.Shared.Views/Content/ForcedUpdate/ForcedUpdatePage.xaml.cs, src/app/ApplicationTemplate.Shared.Views/Framework/Launcher/AppStoreUriProvider.cs, src/app/ApplicationTemplate.Shared.Views/Strings/en/Resources.resw, src/app/ApplicationTemplate.Shared.Views/Strings/fr/Resources.resw, src/app/ApplicationTemplate.Tests.Functional/ForceUpdate/ForceUpdatesShould.cs, src/app/ApplicationTemplate.Tests.Functional/FunctionalTestBase.cs
Implemented a forced update feature
- Update `Architecture.md` and its diagrams …
=> feat: add a forced update feature

CHANGELOG.md, doc/Architecture.md, doc/KillSwitch.md, src/app/ApplicationTemplate.Access/ApiClients/KillSwitch/IKillSwitchRepository.cs, src/app/ApplicationTemplate.Access/ApiClients/KillSwitch/KillSwitchRepositoryMock.cs, src/app/ApplicationTemplate.Business/KillSwitch/IKillSwitchService.cs, src/app/ApplicationTemplate.Business/KillSwitch/KillSwitchService.cs, src/app/ApplicationTemplate.Presentation/Configuration/ApiConfiguration.cs, src/app/ApplicationTemplate.Presentation/Configuration/AppServicesConfiguration.cs, src/app/ApplicationTemplate.Presentation/CoreStartup.cs, src/app/ApplicationTemplate.Presentation/ViewModels/Diagnostics/Navigation/NavigationDebuggerViewModel.cs, src/app/ApplicationTemplate.Presentation/ViewModels/KillSwitchPageViewModel.cs, src/app/ApplicationTemplate.Shared.Views/ApplicationTemplate.Shared.Views.projitems, src/app/ApplicationTemplate.Shared.Views/Configuration/NavigationConfiguration.cs, src/app/ApplicationTemplate.Shared.Views/Content/Diagnostics/NavigationDebuggerView.xaml, src/app/ApplicationTemplate.Shared.Views/Content/KillSwitch/KillSwitchPage.xaml, src/app/ApplicationTemplate.Shared.Views/Content/KillSwitch/KillSwitchPage.xaml.cs, src/app/ApplicationTemplate.Shared.Views/Strings/en/Resources.resw, src/app/ApplicationTemplate.Shared.Views/Strings/fr/Resources.resw, src/app/ApplicationTemplate.Tests.Functional/ForceUpdate/ForceUpdatesShould.cs, src/app/ApplicationTemplate.Tests.Functional/FunctionalTestBase.cs, src/app/ApplicationTemplate.Tests.Functional/KillSwitch/KillSwitchShould.cs
- Update `Architecture.md` and its diagrams if you made **architecture …
=> feat: added kill switch

CHANGELOG.md, src/app/ApplicationTemplate.Presentation/ViewModels/Posts/PostItemViewModel.cs, src/app/ApplicationTemplate.Presentation/ViewModels/Posts/PostsPageViewModel.cs, src/app/ApplicationTemplate.Shared.Views/Content/Posts/PostsPage.xaml, src/app/ApplicationTemplate.Tests.Functional/Posts/EditPostPageViewModelShould.cs
Now we can use the edit and delete buttons on Android in the posts page.
See https://github.com/unoplatform/uno/issues/13996 for more details.
- …
=> fix: Workaround for Posts page

.github/PULL_REQUEST_TEMPLATE.md
fix changeLog file url on PR template …
=> fix(293338): fix changeLog file url on PR template

.azure-pipelines.yml, CHANGELOG.md
I've made sure that the CI task to release the nv template mobile nuget can only be executed from the main branch
- Update `Diagnostics.md` if you …
=> ci: ensure nuget release is only executed from the main branch

CHANGELOG.md, src/app/ApplicationTemplate.Access/ApplicationTemplate.Access.csproj
Updating the Refit package version from 7.0.0 to 8.0.0 to address security advisory
- Update `Diagnostics.md` if you made changes to **diagnostic …
=> fix: update refit package to address security advisory

CHANGELOG.md, src/app/ApplicationTemplate.Mobile/ApplicationTemplate.Mobile.csproj, src/app/ApplicationTemplate.Shared.Views/ApplicationTemplate.Shared.Views.projitems, src/app/ApplicationTemplate.Shared.Views/Behaviors/CommandBarSafeAreaBehavior.cs, src/app/ApplicationTemplate.Shared.Views/Styles/Controls/CommandBar.xaml
Uno update broke the safearea again so applying workaround. 
- Update …
=> fix: Safe area at the top is broken

CHANGELOG.md, src/app/ApplicationTemplate.Shared.Views/Styles/Controls/CommandBar.xaml
The commandbar height property was not needed and causing problems on windows. Plus on other projects we either don't set it or we set it to 48 manually which is the value in uno.material. I found that even without the setter the commandbar has the same height by default.
- Update `README.md` and `TemplateConfig.md` if …
=> fix: Missing material resource key MaterialCommandBarHeight

CHANGELOG.md, build/templates/validate-commits.yaml
I fixed the commits validator for [this](https://github.com/nventive/UnoApplicationTemplate/pull/430) pull request.
[Source](https://github.com/nventive/FlutterApplicationTemplate/pull/54).
- Update `AzurePipelines.md` and …
=> ci: Fix Commits Validator

CHANGELOG.md, src/app/ApplicationTemplate.Access/Configuration/SerializationConfiguration.cs, src/app/ApplicationTemplate.Presentation/Configuration/ApiConfiguration.cs
- The Refit serializer now properly uses the `JsonSerializerOptions` that has code generated deserializers and serializers (the one that refers `JsonContext`).
- Update `AzurePipelines.md` and `APP_README.md` if you made changes to …
=> fix: Properly use the JsonContext for Refit serialization.

CHANGELOG.md, doc/Configuration.md, src/app/ApplicationTemplate.Shared.Views/Behaviors/CommandBarSafeAreaBehavior.cs
I'm updating the documentation for the ConfigurationConfiguration file because it was referencing AppSettingsConfiguration which was what we had before. Also updating the workaround for the uno commandbar safe area bug because the fix is coming in 5.7.0 or a backport in 5.6.0 which isn't happening yet.
- Update …
=> doc: Updating configuration documentation and uno workaround

CHANGELOG.md, build/steps-build-android.yml, build/steps-build-ios.yml, build/steps-build-tests.yml, build/templates/dotnet-install.yml
I optimized the .NET workloads install process by only installing the required workloads depending on the platform.
- Update `Diagnostics.md` if you …
=> fix: Optimize .NET install

CHANGELOG.md, src/app/ApplicationTemplate.Presentation/ViewModels/Extensions/ISectionsNavigator.Extensions.cs, src/app/ApplicationTemplate.Tests.Functional/ForceUpdate/ForceUpdatesShould.cs, src/app/ApplicationTemplate.Tests.Functional/FunctionalTestBase.cs, src/app/ApplicationTemplate.Tests.Functional/Posts/EditPostPageViewModelShould.cs
Make sure the view models are disposed of at the end of each functional test.
- …
=> fix: Add VM Disposal in Tests

CHANGELOG.md, src/app/ApplicationTemplate.Shared.Views/Configuration/LocalizationConfiguration.cs
Since migrating from net 6 there's a bug where on android the current culture doesn't return the "current" culture but rather the one that was current when the app was installed so im adding the workaround we added on other projects
- …
=> fix: Adding workaround for language bug
