nventive/UnoApplicationTemplate

.azure-pipelines.app.yml, src/app/ApplicationTemplate.Droid/ApplicationTemplate.Droid.csproj
=> Update to the new DX compiler for Android and align nuget version with VS

src/app/ApplicationTemplate.Droid/ApplicationTemplate.Droid.csproj, src/app/ApplicationTemplate.Shared/Presentation/Diagnostics/DiagnosticsOverlayViewModel.cs, src/app/ApplicationTemplate.UWP/ApplicationTemplate.UWP.csproj, src/app/ApplicationTemplate.UWP/Views/Content/Diagnostics/DiagnosticsOverlay.xaml, src/app/ApplicationTemplate.UWP/Views/Shell.xaml, src/app/ApplicationTemplate.Wasm/ApplicationTemplate.Wasm.csproj, src/app/ApplicationTemplate.iOS/ApplicationTemplate.iOS.csproj
- Feature
I've added the AlignmentGrid control in the shell.
N/A
N/A
=> Add alignmentgrid in the shell

src/app/ApplicationTemplate.Droid/ApplicationTemplate.Droid.csproj, src/app/ApplicationTemplate.Shared/Configuration/AppServicesConfiguration.cs, src/app/ApplicationTemplate.Shared/CoreStartup.cs, src/app/ApplicationTemplate.Tests/ApplicationTemplate.Tests.csproj, src/app/ApplicationTemplate.UWP/ApplicationTemplate.UWP.csproj, src/app/ApplicationTemplate.iOS/ApplicationTemplate.iOS.csproj
- Bugfix
- Feature
Bump packages and changes ExtendedSplashScreen dismiss
=> Update packages + Dismiss SplashScreen

src/app/ApplicationTemplate.Droid/ApplicationTemplate.Droid.csproj, src/app/ApplicationTemplate.Wasm/ApplicationTemplate.Wasm.csproj, src/app/ApplicationTemplate.iOS/ApplicationTemplate.iOS.csproj
Fixes https://github.com/unoplatform/uno/issues/3504
- Bugfix
Preemptive fix for Uno 3.0
Similar PR here https://dev.azure.com/nventive/Uno%20Gallery/_git/Uno%20Gallery/pullrequest/29338?discussionId=257054&_a=files&path=%2FUno.Gallery%2FUno.Gallery.Droid%2FUno.Gallery.Droid.csproj
=> fix: Fix App.xaml link + add hotreload

src/app/ApplicationTemplate.Shared.Views/ApplicationTemplate.Shared.Views.projitems, src/app/ApplicationTemplate.Shared.Views/Configuration/FluentValidationLanguageManager.cs, src/app/ApplicationTemplate.Shared/CoreStartup.cs, src/app/ApplicationTemplate.Shared/Presentation/Authentication/LoginFormViewModel.cs, src/app/ApplicationTemplate.Shared/Strings/en/Resources.resw, src/app/ApplicationTemplate.Shared/Strings/fr/Resources.resw
- Feature
Added examples of customizing the localization offered by FluentValidations.
=> Demonstrate localization with FluentValidation

src/app/ApplicationTemplate.Shared/ApplicationTemplate.Shared.projitems, src/app/ApplicationTemplate.Shared/Configuration/ConfigurationSettings.cs, src/app/ApplicationTemplate.Shared/Configuration/DiagnosticsConfiguration.cs, src/app/ApplicationTemplate.Shared/Configuration/LoggingConfiguration.cs, src/app/ApplicationTemplate.Shared/Presentation/Diagnostics/DiagnosticsOverlayViewModel.cs, src/app/ApplicationTemplate.Shared/Presentation/Diagnostics/LoggersDiagnosticsViewModel.cs, src/app/ApplicationTemplate.Shared/Presentation/Diagnostics/SettingsDiagnosticsViewModel.cs, src/app/ApplicationTemplate.UWP/Views/Content/Diagnostics/DiagnosticsOverlay.xaml, src/app/ApplicationTemplate.UWP/Views/Content/Diagnostics/DiagnosticsPage.xaml, src/app/ApplicationTemplate.UWP/Views/Shell.xaml
- Feature
Cleans the diagnostics overlay and adds the ability to disable it in debug.
=> feat(diags): Cleans the diagnostics overlay and adds the ability to disable it in debug.

.azure-pipelines.yml, Directory.Build.props, build/stage-build.yml, build/stage-release-appcenter.yml, build/stage-release-googleplay.yml, build/steps-build-wasm.yml, build/steps-build.yml, src/app/ApplicationTemplate.Droid/ApplicationTemplate.Droid.csproj, src/app/ApplicationTemplate.Shared/ApplicationTemplate.Shared.projitems, src/app/ApplicationTemplate.Shared/appsettings.production.json
Updates the pipeline to support additional scenarios.
=> Updates the pipeline to support additional scenarios.

src/app/ApplicationTemplate.Shared/appsettings.production.json
Renames the production environment in the appsettings.
=> Renames the production environment in the appsettings.

README.md, doc/Configuration.md, doc/DataLoading.md, doc/DependencyInjection.md, doc/Environments.md, doc/ErrorHandling.md, doc/HTTP.md, doc/Localization.md, doc/Logging.md, doc/Mvvm.md, doc/Navigation.md, doc/PlatformSpecifics.md, doc/Scheduling.md, doc/Serialization.md, doc/Testing.md, doc/Validation.md, src/ApplicationTemplate.sln
=> Adds a lot of documentation.

.azure-pipelines.yml
- Updated comment 
- Updated comment to be clearer on how to run or not jobs in parallel 
=> Updated comment for clearer instructions

src/app/ApplicationTemplate.Droid/ApplicationTemplate.Droid.csproj
- Bugfix
Allow the app to be deployed on an Android emulator
=> chore: Allow deployment on emulator

.editorconfig, src/app/ApplicationTemplate.Shared.Views/Startup.cs, src/app/ApplicationTemplate.Shared/Business/IChuckNorrisService.cs, src/app/ApplicationTemplate.Shared/Business/Impl/ChuckNorrisService.cs, src/app/ApplicationTemplate.Shared/Configuration/LocalizationConfiguration.cs, src/app/ApplicationTemplate.Shared/CoreStartup.cs, src/app/ApplicationTemplate.Shared/Framework/BaseMock.cs, src/app/ApplicationTemplate.Shared/Framework/DynamicData/IChangeSet.Extensions.cs, src/app/ApplicationTemplate.Shared/Framework/DynamicMvvm/IViewModel.Extensions.cs, src/app/ApplicationTemplate.Shared/Framework/Reactive/IObservable.Extensions.cs, src/app/ApplicationTemplate.Shared/Framework/Startup/CoreStartupBase.cs, src/app/ApplicationTemplate.Shared/Framework/Startup/StartupBase.cs, src/app/ApplicationTemplate.Shared/Framework/Validation/DataValidationState.cs, src/app/ApplicationTemplate.Shared/Presentation/Diagnostics/ExceptionsDiagnosticsViewModel.cs, src/app/ApplicationTemplate.Shared/Presentation/Diagnostics/SettingsDiagnosticsViewModel.cs, src/app/ApplicationTemplate.Shared/Presentation/MenuViewModel.cs, src/app/ApplicationTemplate.Shared/Presentation/Posts/EditPostPageViewModel.cs, src/app/ApplicationTemplate.Tests/ApplicationTemplate.Tests.csproj, src/app/ApplicationTemplate.Tests/Presentation/PostsPageViewModelTests.cs, src/app/ApplicationTemplate.UWP/ApplicationTemplate.UWP.csproj
Refactoring
Fixes all warnings.
=> Fixes all warnings.

.editorconfig, src/app/ApplicationTemplate.UWP/ApplicationTemplate.UWP.csproj
=> Fixes more warnings.

.azure-pipelines.yml, build/stage-release-appcenter.yml, build/stage-release-appstore.yml, build/stage-release-googleplay.yml, build/stage-release-wasm.yml
Adds deployment environments which allows manual approvals.
=> Adds deployment environments which allows manual approvals.

doc/Testing.md, src/app/ApplicationTemplate.Tests/TestBase.cs
- Feature
Adds support of mocked services in an integration test.
=> Adds support of mocked services in an integration test.

build/steps-build.yml, doc/Testing.md, src/app/ApplicationTemplate.Tests/ApplicationTemplate.Tests.csproj
- Feature
Adds code coverage support using coverlet inside the build steps.
=> Adds code coverage support using coverlet inside the build steps.

src/app/ApplicationTemplate.Shared/Presentation/Diagnostics/DiagnosticsOverlayViewModel.cs, src/app/ApplicationTemplate.Shared/Presentation/Settings/SettingsPageViewModel.cs
- Bugfix
Removing diagnostics page from PRODUCTION build by default
=> Remove diagnostics page from PROD environment

src/app/ApplicationTemplate.Shared/ApplicationTemplate.Shared.projitems, src/app/ApplicationTemplate.Shared/Configuration/AppServicesConfiguration.cs, src/app/ApplicationTemplate.Shared/Framework/Browser/DispatcherBrowserDecorator.cs, src/app/ApplicationTemplate.Shared/Presentation/Settings/SettingsPageViewModel.cs
- Feature
Add DispatcherBrowserDecorator, which wraps an IBrowser service and schedules requests to the service on the dispatcher. This prevents thread errors and is simpler than asking the consumer of the IBrowser to schedule every call itself.
=> feat: Add DispatcherBrowserDecorator

src/app/ApplicationTemplate.Droid/Application.cs, src/app/ApplicationTemplate.Droid/ApplicationTemplate.Droid.csproj, src/app/ApplicationTemplate.UWP/ApplicationTemplate.UWP.csproj, src/app/ApplicationTemplate.UWP/Views/Styles/Controls/Frame.xaml, src/app/ApplicationTemplate.Wasm/ApplicationTemplate.Wasm.csproj, src/app/ApplicationTemplate.iOS/ApplicationTemplate.iOS.csproj
- Update to Uno.UI 3.1.0-beta.84
Update to Uno.UI 3.1.0-beta.84, including dependencies
=> chore: Update to Uno.UI 3.1.0-beta.84

.azure-pipelines.yml, src/app/ApplicationTemplate.Shared/Configuration/AppServicesConfiguration.cs
Added the trigger instruction in the pipeline definition.
=> Added pr triggers

src/app/ApplicationTemplate.Tests/ApplicationTemplate.Tests.csproj
- Bumped Chinook package to same version as heads one for Tests project. 
=> Bump version for project Tests

src/app/ApplicationTemplate.Droid/ApplicationTemplate.Droid.csproj, src/app/ApplicationTemplate.UWP/ApplicationTemplate.UWP.csproj, src/app/ApplicationTemplate.iOS/ApplicationTemplate.iOS.csproj
=> chore: Update to Uno.UI 3.1.10

src/app/ApplicationTemplate.Droid/ApplicationTemplate.Droid.csproj, src/app/ApplicationTemplate.Droid/MainActivity.cs, src/app/ApplicationTemplate.Shared/Configuration/ApiConfiguration.cs, src/app/ApplicationTemplate.Shared/Configuration/ErrorConfiguration.cs, src/app/ApplicationTemplate.Shared/CoreStartup.cs, src/app/ApplicationTemplate.Shared/Framework/FirebasePerformanceHandler.cs, src/app/ApplicationTemplate.Tests/ApplicationTemplate.Tests.csproj, src/app/ApplicationTemplate.UWP/App.xaml.cs, src/app/ApplicationTemplate.UWP/ApplicationTemplate.UWP.csproj, src/app/ApplicationTemplate.iOS/ApplicationTemplate.iOS.csproj
- Bugfix
I've basically updated UnoApplicationTemplate packages to latest version which means the following:
- Update Uno to 3.4.0
- Update firebase sdk to latest stable version (without fabric)
- Update three packages to its latest stable version (DynamicData, MallardMessageHandler and FluentValidation.DependencyInjectionExtensions)
I also did fix bugs that I've found while working on a project which started from this template
- FirebasePerformanceHandler was crashing for specific request (POST), because the request is disposed after it's completed
- Cannot build on iOS, because AddFirebaseHandler does not return something on other platform
=> Update UnoApplicationTemplate packages to latest stable version (Including Uno) + quick fixes

src/app/ApplicationTemplate.Shared/ApplicationTemplate.Shared.projitems, src/app/ApplicationTemplate.Shared/Business/Entities/ChuckNorrisQuote.cs, src/app/ApplicationTemplate.Shared/Presentation/Extensions/SectionNavigatorExtensions.cs, src/app/ApplicationTemplate.Tests/Business/PostServiceTests.cs, src/app/ApplicationTemplate.Tests/Client/ChuckNorrisEndpointTests.cs, src/app/ApplicationTemplate.Tests/Client/PostEndpointTests.cs, src/app/ApplicationTemplate.Tests/Presentation/ChuckNorrisFavoritesPageViewModel.cs, src/app/ApplicationTemplate.Tests/Presentation/ChuckNorrisSearchPageViewModelTests.cs, src/app/ApplicationTemplate.Tests/Presentation/NavigationTests.cs, src/app/ApplicationTemplate.Tests/Presentation/NavigationTestsBase.cs, src/app/ApplicationTemplate.Tests/Presentation/PostsPageViewModelTests.cs, src/app/ApplicationTemplate.Tests/TestBase.cs
- Other (integration tests)
We've added integration tests on UnoApplicationTemplate
=> Started implementation of integration tests

.azure-pipelines.yml, build/stage-build.yml, build/steps-build.yml
- 
Add Canary to Uno Application Template
=> Add Canary 

.azure-pipelines.yml
=> Add package author to canary update

src/app/ApplicationTemplate.Wasm/ApplicationTemplate.Wasm.csproj
- Bugfix
Update Web Assembly packages to use the right packages.
Uno.UI.WebAssembly has replaced Uno.UI for the new packages
=> Update Web Assembly packages

.azure-pipelines.yml
- Bugfix
Add slug for uwp Canary + fix typo
=> Add slug for uwp + typo

.azure-pipelines.yml, build/stage-release-appcenter.yml
- Pass the iOS VariableGroup as a parameter instead of hardcoding it in the stage file.
=> Fix missing mapping for iOS AppCenter release

CHANGELOG.md, src/app/ApplicationTemplate.Droid/ApplicationTemplate.Droid.csproj, src/app/ApplicationTemplate.Droid/Properties/AndroidManifest.xml, src/app/ApplicationTemplate.Tests/ApplicationTemplate.Tests.csproj, src/app/ApplicationTemplate.UWP/ApplicationTemplate.UWP.csproj, src/app/ApplicationTemplate.iOS/ApplicationTemplate.iOS.csproj
- Feature
Initial work on Android 11 support
~~- [ ] Interface members are XML documented~~
~~- [ ] Documentation (XML or comments) has been added and/or existing documentation has been updated~~
~~- [ ] [Architecture documents](./doc/Architecture.md) have been updated~~
=> Updates Chinook packages that now target Android 11

doc/BuildPipeline.md
Adds a detailed description of the build definition.
=> doc: Adds build pipeline documentation

build/stage-release-appcenter.yml
Fixes a mismatch in the path used by the APK creation step and the release to App Center.
=> ci: fixes release of the APK to App Center

src/app/ApplicationTemplate.Droid/ApplicationTemplate.Droid.csproj, src/app/ApplicationTemplate.Shared/Business/Impl/ChuckNorrisService.cs, src/app/ApplicationTemplate.Tests/ApplicationTemplate.Tests.csproj, src/app/ApplicationTemplate.UITests/ApplicationTemplate.UITests.csproj, src/app/ApplicationTemplate.UWP/ApplicationTemplate.UWP.csproj, src/app/ApplicationTemplate.Wasm/ApplicationTemplate.Wasm.csproj, src/app/ApplicationTemplate.iOS/ApplicationTemplate.iOS.csproj
=> update: Update Uno packages

src/app/ApplicationTemplate.UWP/App.xaml.cs, src/app/ApplicationTemplate.UWP/Views/Shell.xaml.cs
- Feature
- Makes sure the app doesn't stay on the splashscreen if you launch it from custom schemes or links.
=> feat: Adapt App.xaml.cs to support launching from Uri.

src/app/ApplicationTemplate.UITests/ApplicationTemplate.UITests.csproj, src/app/ApplicationTemplate.UITests/Constants.cs, src/app/ApplicationTemplate.UITests/TestBase.cs, src/app/ApplicationTemplate.UITests/Tests/StartupTests.cs
- Feature
Re enabling UI Tests in the UnoApplicationTemplate
=> feat: Re enabling UITests in the UnoApplicationTemplate

src/app/ApplicationTemplate.Droid/ApplicationTemplate.Droid.csproj
Bumping TargetFrameworkVersion to v11.0 so we're actually using android 11 API.
=> chore: bump TargetFrameworkVersion to 11.0

.azure-pipelines.yml, build/canary-merge.yml, build/stage-build.yml, build/steps-build.yml
Canary model was changed from branch-less to creating a branch per canary build.
=> ci: changed canary model to create branches

build/canary-merge.yml
Fixed syntax issue in the canary merge definition
=> ci: fixed syntax error in canary merge

.azure-pipelines.yml, build/canary-merge.yml, build/stage-build.yml, build/stage-release-appcenter.yml, build/steps-build.yml
=> Merge master into Canary dev

src/app/ApplicationTemplate.Droid/ApplicationTemplate.Droid.csproj, src/app/ApplicationTemplate.UWP/ApplicationTemplate.UWP.csproj, src/app/ApplicationTemplate.Wasm/ApplicationTemplate.Wasm.csproj, src/app/ApplicationTemplate.iOS/ApplicationTemplate.iOS.csproj
=> Update Uno.UI to latest stable

src/app/ApplicationTemplate.Shared/Configuration/SerializationConfiguration.cs
- Feature
Add Refit.ProblemDetails to the SerializationConfiguration the serializationConfig so we properly deserialize api call issues.
https://dev.azure.com/nventive/OneFlow/_git/OneFlow.Spaces/pullrequest/35608?discussionId=306803&path=%2Fsrc%2Fapp%2FOneFlow.Spaces.Shared%2FConfiguration%2FSerializationConfiguration.cs
=> feat: Add Refit.ProblemDetails to the SerializationConfiguration the serializationConfig so we properly deserialize api call issues.

src/app/ApplicationTemplate.Shared/ApplicationTemplate.Shared.projitems, src/app/ApplicationTemplate.Shared/Presentation/Authentication/CreateAccountFormViewModel.cs, src/app/ApplicationTemplate.Shared/Presentation/Authentication/CreateAccountPageViewModel.cs, src/app/ApplicationTemplate.Shared/Presentation/Extensions/ValidatorExtensions.cs, src/app/ApplicationTemplate.Shared/Strings/en/Resources.resw, src/app/ApplicationTemplate.Shared/Strings/fr/Resources.resw, src/app/ApplicationTemplate.UWP/Views/Content/Authentication/CreateAccountPage.xaml, src/app/ApplicationTemplate.UWP/Views/Styles/Controls/ListViewItem.xaml
- Feature
Adding more complex example of fluent validation
=> feat: Add validation rules to create account

src/app/ApplicationTemplate.Shared/ApplicationTemplate.Shared.projitems, src/app/ApplicationTemplate.Shared/Configuration/ApiConfiguration.cs, src/app/ApplicationTemplate.Shared/Configuration/ChuckNorrisEndpointOptions.cs, src/app/ApplicationTemplate.Shared/Configuration/EndpointOptions.cs, src/app/ApplicationTemplate.Shared/Configuration/_Configuration.cs, src/app/ApplicationTemplate.Shared/Framework/Configuration/IConfigurationExtensions.cs, src/app/ApplicationTemplate.Shared/Framework/DependencyInjection/RegistrationServiceCollectionExtensions.cs
- Feature
Add a recipe to load configuration sections and register them for DI
Based on the backend template recipe to make it easier to use and maintain
NA
NA
=> Add a recipe to load configuration sections and register them for DI

.azure-pipelines.yml, build/stage-release-appcenter.yml, build/steps-build.yml, build/variables.yml, src/app/ApplicationTemplate.UWP/ApplicationTemplate.UWP.csproj
=> Update SDK and pipeline for latest version

Directory.Build.props
Improved build performance by instructing MSBuild to use hard links instead of copying files
=> chore: Improved build performance

.azure-pipelines.yml
Comment scheduled builds so that a build is not scheduled everyday
=> Comment scheduled builds

src/app/ApplicationTemplate.UWP/Views/Content/DadJokes/DadJokesPage.xaml
Temporary commented code until phase 2
=> Hide Dad Jokes filters navigation btn to keep for phase 2

src/app/ApplicationTemplate.UWP/Views/Styles/Controls/HyperlinkButton.xaml
- Clean the styles of the hyperlink control
- Remove duplicated code from Themes and unnecessary styles for the project
- Using Uno.Themes styles as much as possible
https://nventive.visualstudio.com/Practice%20committees/_backlogs/backlog/Mobile%20(.Net)/Features/?workitem=252663
=> Review and cleaning of the hyperlink control styles

.mergify.yml
=> chore: fix mergify configuration

src/app/ApplicationTemplate.UWP/Views/Content/Authentication/CreateAccountPage.xaml, src/app/ApplicationTemplate.UWP/Views/Content/Authentication/LoginPage.xaml, src/app/ApplicationTemplate.UWP/Views/Styles/Controls/PasswordBox.xaml
- Remove the template from the custom control, use Uno.Themes Material instead
- Keep the same basic setters as the TextBoxStyle used for other inputs
- Format pages files
https://nventive.visualstudio.com/Practice%20committees/_backlogs/backlog/Mobile%20(.Net)/Features/?workitem=252666
=> Review and cleaning of the PasswordBox control styles

build/stage-build.yml
Remove Install .net core from stage-build.yml since it's already in steps-build.yml
=> Cleanup Install .net core step

src/app/ApplicationTemplate.UWP/Views/Content/DadJokes/DadJokesPage.xaml, src/app/ApplicationTemplate.UWP/Views/Styles/Controls/ListView.xaml
- Clean the styles of the hyperlink control
- Remove duplicated code from Themes and unnecessary styles for the project
- Using Uno.Themes styles as much as possible
- Kept commented setter
- Kept previous control Template to make sure that we keep the ScrollViewer that wasn't included in the base of the Uno.Theme control
https://nventive.visualstudio.com/Practice%20committees/_backlogs/backlog/Mobile%20(.Net)/Features/?workitem=252664
=> Review and cleaning of the ListView control styles

src/app/ApplicationTemplate.UWP/Views/Content/DadJokes/DadJokesFavoritesPage.xaml, src/app/ApplicationTemplate.UWP/Views/Content/DadJokes/DadJokesPage.xaml, src/app/ApplicationTemplate.UWP/Views/Content/DadJokes/DadJokesSearchPage.xaml, src/app/ApplicationTemplate.UWP/Views/Styles/Controls/PathControl.xaml, src/app/ApplicationTemplate.UWP/Views/Styles/Controls/ToggleButton.xaml
- Remove custom ToggleButton style only used for the heart toggle
- Usage of the MaterialToggleButtonIconStyle
https://nventive.visualstudio.com/Practice%20committees/_backlogs/backlog/Mobile%20(.Net)/Features/?workitem=252676
=> Review and cleaning of the ToggleButton control styles

src/app/ApplicationTemplate.Shared/Strings/en/Resources.resw, src/app/ApplicationTemplate.Shared/Strings/fr/Resources.resw, src/app/ApplicationTemplate.UWP/Views/Content/Authentication/LoginPage.xaml, src/app/ApplicationTemplate.UWP/Views/Content/Posts/EditPostPage.xaml, src/app/ApplicationTemplate.UWP/Views/Content/Settings/EditProfilePage.xaml, src/app/ApplicationTemplate.UWP/Views/Styles/Controls/TextBox.xaml
- Usage of MaterialOutlinedTextBoxStyle as default control
- Remove the custom template
- Keep basic style setters
https://nventive.visualstudio.com/Practice%20committees/_backlogs/backlog/Mobile%20(.Net)/Features/?workitem=252675
=> Review and cleaning of the TextBox control styles

src/app/ApplicationTemplate.UWP/Views/Content/DadJokes/DadJokesFavoritesPage.xaml, src/app/ApplicationTemplate.UWP/Views/Content/DadJokes/DadJokesFiltersPage.xaml, src/app/ApplicationTemplate.UWP/Views/Content/DadJokes/DadJokesPage.xaml, src/app/ApplicationTemplate.UWP/Views/Content/DadJokes/DadJokesSearchPage.xaml, src/app/ApplicationTemplate.UWP/Views/Content/Posts/PostsPage.xaml, src/app/ApplicationTemplate.UWP/Views/Content/Settings/LicensesPage.xaml, src/app/ApplicationTemplate.UWP/Views/Content/Settings/SettingsPage.xaml, src/app/ApplicationTemplate.UWP/Views/Styles/Controls/CommandBar.xaml, src/app/ApplicationTemplate.UWP/Views/Styles/Controls/DataLoaderView.xaml, src/app/ApplicationTemplate.UWP/Views/Styles/Controls/DataValidationView.xaml, src/app/ApplicationTemplate.UWP/Views/Styles/Controls/TextBlock.xaml
- Clean the control styles
- Keeping the styles only for fonts adjustments purposes
- Remove setters that are the same as the control BasedOn material
- Remove the old custom Default style
https://nventive.visualstudio.com/Practice%20committees/_backlogs/backlog/Mobile%20(.Net)/Features/?workitem=252670
=> Review and cleaning of the TextBlock control styles

src/app/ApplicationTemplate.Shared.Views/Behaviors/FormattingTextBoxBehavior.Android.cs, src/app/ApplicationTemplate.Shared.Views/Behaviors/FormattingTextBoxBehavior.cs, src/app/ApplicationTemplate.Shared.Views/Behaviors/FormattingTextBoxBehavior.iOS.cs, src/app/ApplicationTemplate.Shared.Views/Helpers/DependencyObjectExtensions.cs, src/app/ApplicationTemplate.Shared.Views/Helpers/ObservableExtensions.cs, src/app/ApplicationTemplate.Shared/Business/Impl/DadJokesService.cs, src/app/ApplicationTemplate.Shared/CoreStartup.cs, src/app/ApplicationTemplate.Shared/Framework/Startup/StartupBase.cs, src/app/ApplicationTemplate.Shared/Presentation/Authentication/CreateAccountFormViewModel.cs, src/app/ApplicationTemplate.Shared/Presentation/DadJokes/DadJokesFiltersPageViewModel.cs, src/app/ApplicationTemplate.UITests/Constants.cs, src/app/ApplicationTemplate.UITests/TestBase.cs, src/app/ApplicationTemplate.UWP/Views/Content/DadJokes/DadJokesFavoritesPage.xaml, src/app/ApplicationTemplate.UWP/Views/Content/DadJokes/DadJokesSearchPage.xaml, src/app/ApplicationTemplate.UWP/Views/Content/Menu.xaml.cs, src/app/ApplicationTemplate.UWP/Views/Content/Welcome/OnboardingPage.xaml, src/app/ApplicationTemplate.UWP/Views/Styles/Controls/Button.xaml, src/app/ApplicationTemplate.UWP/Views/Styles/Controls/GridViewItem.xaml
Cleanup code and fix some warnings
=> Cleanup code and fix some warnings

README.md
Update documentation to install and uninstall template
=> Update documentation to create template

src/app/ApplicationTemplate.iOS/Info.plist
- Update
Set iOS min version to 13 to reflect nventive mobile guidelines
=> Set iOS min version to 13

src/app/ApplicationTemplate.Shared.Views/Startup.cs, src/app/ApplicationTemplate.Shared/CoreStartup.cs, src/app/ApplicationTemplate.Shared/Presentation/Extensions/SectionNavigatorExtensions.cs, src/app/ApplicationTemplate.UWP/Views/Content/Settings/SettingsPage.xaml.cs
- Bugfix
Fix StatusBar color
Color change depending on the page because of background color changes making the status bar not visible.
https://dev.azure.com/nventive/Practice%20committees/_backlogs/backlog/Mobile%20(.Net)/Features/?workitem=252413
=> Fix StatusBar color

src/app/ApplicationTemplate.UWP/Views/Content/DadJokes/DadJokesPage.xaml, src/app/ApplicationTemplate.UWP/Views/Content/Menu.xaml, src/app/ApplicationTemplate.UWP/Views/Content/Posts/PostsPage.xaml, src/app/ApplicationTemplate.UWP/Views/Content/Settings/SettingsPage.xaml, src/app/ApplicationTemplate.UWP/Views/Shell.xaml, src/app/ApplicationTemplate.UWP/Views/Styles/Application/LayoutConstants.xaml
- Bugfix
Bottom bar margin is removed
https://dev.azure.com/nventive/Practice%20committees/_backlogs/backlog/Mobile%20(.Net)/Features/?workitem=238538
=> Fix: Bottom bar margin is removed

src/app/ApplicationTemplate.UWP/Views/Content/Settings/EditProfilePage.xaml
=> feat: Clean up EditProfilePage.xaml

src/app/ApplicationTemplate.UWP/Views/Content/Welcome/OnboardingPage.xaml
=> feat: Clean up OnboardingPage.xaml

src/app/ApplicationTemplate.UWP/Views/Content/Diagnostics/DiagnosticsOverlay.xaml
=> feat: Clean up DiagnosticsOverlay.xaml

src/app/ApplicationTemplate.UWP/Views/Content/DadJokes/DadJokesSearchPage.xaml
=> feat: Clean up DadJokesSearchPage.xaml

src/app/ApplicationTemplate.UWP/Views/Content/DadJokes/DadJokesPage.xaml
=> feat: Clean up DadJokesPage.xaml

src/app/ApplicationTemplate.UWP/Views/Content/DadJokes/DadJokesFiltersPage.xaml
=> feat: DadJokesFiltersPage.xaml

src/app/ApplicationTemplate.UWP/Views/Content/Authentication/ForgotPasswordPage.xaml
=> feat: Clean up ForgotPasswordPage.xaml

src/app/ApplicationTemplate.Shared.Views/Startup.cs, src/app/ApplicationTemplate.Shared/Presentation/Authentication/CreateAccountPageViewModel.cs, src/app/ApplicationTemplate.Shared/Presentation/Authentication/PasswordFormViewModel.cs, src/app/ApplicationTemplate.Shared/Presentation/Authentication/ResetPasswordPageViewModel.cs, src/app/ApplicationTemplate.UWP/Views/Styles/Controls/CheckBox.xaml, src/app/ApplicationTemplate.UWP/Views/Styles/Controls/ListViewItem.xaml
- Bugfix
Update checkbox style to handle color change.
Show password validation hints when no password is entered.
https://dev.azure.com/nventive/Practice%20committees/_backlogs/backlog/Mobile%20(.Net)/Features/?workitem=255989
https://dev.azure.com/nventive/Practice%20committees/_backlogs/backlog/Mobile%20(.Net)/Features/?workitem=255990
=> Fix password validation and checkbox style

src/app/ApplicationTemplate.UWP/Views/Content/Authentication/LoginPage.xaml
- Feature
General clean up of the xaml file that include stuff like: 
Clean up LoginPage.xaml
https://dev.azure.com/nventive/Practice%20committees/_workitems/edit/259216
=> feat: Clean up LoginPage.xaml

src/app/ApplicationTemplate.UWP/Views/Content/Welcome/WelcomePage.xaml
- Feature
Clean up WelcomePage.xaml
https://dev.azure.com/nventive/Practice%20committees/_workitems/edit/259235
=> feat: Clean up WelcomePage.xaml

src/app/ApplicationTemplate.UWP/Views/Content/Authentication/CreateAccountPage.xaml
- Feature
General clean up of the xaml file that include stuff like: 
Clean up CreateAccountPage.xaml
https://dev.azure.com/nventive/Practice%20committees/_workitems/edit/259214
=> feat: Clean up CreateAccountPage.xaml

src/app/ApplicationTemplate.UWP/Views/Content/Diagnostics/EnvironmentPickerPage.xaml
- Feature
Reorganize the order of properties in control in a more logical manner
Remove unnecessary blend using
Ensure proper use of material color resources
Reorganization of layout (like using stack panels instead of manually defines rows)
Clean up EnvironmentPickerPage.xaml
https://dev.azure.com/nventive/Practice%20committees/_workitems/edit/259228
=> feat: Clean up EnvironmentPickerPage.xaml

src/app/ApplicationTemplate.Shared/Business/IAuthenticationService.cs, src/app/ApplicationTemplate.Shared/Business/Impl/AuthenticationService.cs, src/app/ApplicationTemplate.Shared/Client/IAuthenticationEndpoint.cs, src/app/ApplicationTemplate.Shared/Client/Mock/AuthenticationEndpointMock.cs
- Bugfix
Authenticate user when creating account to show use info in profile page.
https://dev.azure.com/nventive/Practice%20committees/_workitems/edit/255727
=> Add authentication to account creation

src/app/ApplicationTemplate.UWP/Views/Styles/Controls/CommandBar.xaml
- Bugfix
Applied @[kazo0](https://github.com/kazo0) solution so the command bar is displayed correctly whether the status bar is translucent or not
https://dev.azure.com/nventive/Practice%20committees/_backlogs/backlog/Mobile%20(.Net)/Features/?workitem=252898
=> fix: [Android] The CommandBars are not displayed correctly

.azure-pipelines-canary.yml, .azure-pipelines.yml, Directory.Build.props, build/stage-build.yml, build/stage-donetnew.yaml, build/stage-release-appcenter.yml, build/steps-build.yml, build/variables.yml, src/app/ApplicationTemplate.Droid/ApplicationTemplate.Droid.csproj, src/app/ApplicationTemplate.UWP/ApplicationTemplate.UWP.csproj, src/app/ApplicationTemplate.iOS/ApplicationTemplate.iOS.csproj
- Remove Nimue and update to build tools 17.2.5
=> Remove Nimue and update to build tools 17.2.5

src/app/ApplicationTemplate.Presentation/CoreStartup.cs, src/app/ApplicationTemplate.Presentation/Framework/Logging/ThreadIdEnricher.cs, src/app/ApplicationTemplate.Presentation/Framework/Startup/CoreStartupBase.cs, src/app/ApplicationTemplate.Shared.Views/Configuration/LoggingConfiguration.cs, src/app/ApplicationTemplate.Tests/ApplicationTemplate.Tests.csproj, src/app/ApplicationTemplate.Tests/Framework/IntegrationTestBase.cs, src/app/ApplicationTemplate.Tests/Presentation/DadJokesFilterPageViewModelShould.cs, src/app/ApplicationTemplate.Tests/Presentation/NavigationTestsBase.cs, src/app/ApplicationTemplate.Tests/Presentation/PostsPageViewModelShould.cs
- Feature
- Add support for logging in integration tests.
- Add a ThreadIdEnricher for logs on windows.
- Adjust log output template to remove clutter (like date and timezone) for tests and console logs.
=> feat: Add support for logging in integration tests.

src/app/ApplicationTemplate.Presentation/Configuration/AppSettingsConfiguration.cs, src/app/ApplicationTemplate.Presentation/ViewModels/Diagnostics/EnvironmentPickerPageViewModel.cs
- Bugfix
- Restore the environment picker behavior.
=> fix: Restore the environment picker behavior.

src/app/ApplicationTemplate.Business/DadJokes/IDadJokesService.cs, src/app/ApplicationTemplate.Business/Posts/IPostService.cs, src/app/ApplicationTemplate.Business/Posts/Post.cs, src/app/ApplicationTemplate.Business/Posts/PostService.cs, src/app/ApplicationTemplate.Business/UserProfile/IUserProfileService.cs, src/app/ApplicationTemplate.Business/UserProfile/UserProfile.cs, src/app/ApplicationTemplate.Business/UserProfile/UserProfileService.cs, src/app/ApplicationTemplate.Presentation/ViewModels/Posts/EditPostPageViewModel.cs, src/app/ApplicationTemplate.Presentation/ViewModels/Posts/PostFormViewModel.cs, src/app/ApplicationTemplate.Presentation/ViewModels/Posts/PostsPageViewModel.cs, src/app/ApplicationTemplate.Presentation/ViewModels/Settings/EditProfileFormViewModel.cs, src/app/ApplicationTemplate.Presentation/ViewModels/Settings/EditProfilePageViewModel.cs, src/app/ApplicationTemplate.Presentation/ViewModels/Settings/SettingsPageViewModel.cs, src/app/ApplicationTemplate.Tests/Business/PostServiceShould.cs, src/app/ApplicationTemplate.Tests/Presentation/PostsPageViewModelShould.cs
- Bugfix
- Remove usage of client layer data from view models.
=> fix: Remove usage of client layer data from view models

src/app/ApplicationTemplate.Presentation/Framework/ViewModels/IViewModel.Extensions.Options.cs, src/app/ApplicationTemplate.Presentation/ViewModels/Diagnostics/DiagnosticsOverlayViewModel.cs, src/app/ApplicationTemplate.Presentation/ViewModels/Diagnostics/LoggersDiagnosticsViewModel.cs, src/app/ApplicationTemplate.Presentation/ViewModels/Diagnostics/SettingsDiagnosticsViewModel.cs
- Feature
- Add support for dynamic property from IOptionsMonitor.
- Refactor diagnostics pages accordingly.
=> feat: Add support for dynamic property from IOptionsMonitor.

src/app/ApplicationTemplate.Presentation/CoreStartup.cs
- Feature
- Add support and documentation for ViewModel deactivation.
=> feat: Add support and documentation for ViewModel deactivation.

build/steps-build.yml, src/app/ApplicationTemplate.Tests/ApplicationTemplate.Tests.csproj
- Cleanup code coverage configuration to exclude code from test project.
=> build: Cleanup coverlet configuration for code coverage.

src/app/ApplicationTemplate.Presentation/Configuration/ConfigurationConfiguration.cs, src/app/ApplicationTemplate.Presentation/CoreStartup.cs, src/app/ApplicationTemplate.Presentation/Framework/Startup/CoreStartupBase.cs, src/app/ApplicationTemplate.Presentation/Framework/Startup/WritableJsonConfigurationProvider.cs, src/app/ApplicationTemplate.Presentation/Framework/Startup/WritableJsonConfigurationSource.cs, src/app/ApplicationTemplate.Presentation/ViewModels/Diagnostics/DiagnosticsPageViewModel.cs, src/app/ApplicationTemplate.Presentation/ViewModels/Diagnostics/EnvironmentPickerPageViewModel.cs, src/app/ApplicationTemplate.Presentation/ViewModels/Diagnostics/SummaryDiagnosticsViewModel.cs
- Improve naming and documentation for code around IConfiguration.
=> doc: Improve naming and documentation for code around IConfiguration.

.template.config/dotnetcli.host.json, .template.config/template.json, README.md, src/app/ApplicationTemplate.Droid/ApplicationTemplate.Droid.csproj, src/app/ApplicationTemplate.Droid/Resources/values/Strings.xml, src/app/ApplicationTemplate.Presentation/Configuration/ApiConfiguration.cs, src/app/ApplicationTemplate.Presentation/Configuration/ErrorConfiguration.cs, src/app/ApplicationTemplate.Presentation/CoreStartup.cs, src/app/ApplicationTemplate.Shared.Views/Configuration/LinkerConfiguration.cs, src/app/ApplicationTemplate.UWP/App.xaml.cs, src/app/ApplicationTemplate.iOS/ApplicationTemplate.iOS.csproj
- Feature
- Remove the `-fa` / `--include-firebase-analytics` flag from the dotnet new template.
=> chore: Remove the dotnet new include-firebase-analytics flag.

src/app/ApplicationTemplate.Business/ApplicationTemplate.Business.csproj, src/app/ApplicationTemplate.Droid/ApplicationTemplate.Droid.csproj, src/app/ApplicationTemplate.Presentation/ApplicationTemplate.Presentation.csproj, src/app/ApplicationTemplate.Tests/ApplicationTemplate.Tests.csproj, src/app/ApplicationTemplate.UWP/ApplicationTemplate.UWP.csproj, src/app/ApplicationTemplate.iOS/ApplicationTemplate.iOS.csproj
- Feature
- Update Chinook.DynamicMvvm.
- Remove duplicated nuget references.
=> chore: Update chinook and cleanup duplicated nuget references.

src/app/ApplicationTemplate.Presentation/ApplicationTemplate.Presentation.csproj
Fix issue with building app with VS 17.3.0
=> Fix issue with building app with VS 17.3.0

src/app/ApplicationTemplate.Droid/ApplicationTemplate.Droid.csproj, src/app/ApplicationTemplate.Presentation/ApplicationTemplate.Presentation.csproj, src/app/ApplicationTemplate.UITests/ApplicationTemplate.UITests.csproj, src/app/ApplicationTemplate.UWP/ApplicationTemplate.UWP.csproj, src/app/ApplicationTemplate.iOS/ApplicationTemplate.iOS.csproj
- Feature
- Update Uno.UI packages to latest stable.
=> feat: Update Uno.UI packages to latest stable.

doc/Diagnostics.md, doc/HTTP.md, src/app/ApplicationTemplate.Business/ApplicationTemplate.Business.csproj, src/app/ApplicationTemplate.Client/ApplicationTemplate.Client.csproj, src/app/ApplicationTemplate.Client/Framework/Configuration/IConfiguration.Extensions.cs, src/app/ApplicationTemplate.Client/Framework/Configuration/IHttpClientBuilder.Extensions.cs, src/app/ApplicationTemplate.Client/Framework/HttpDebugger/HttpDebuggerHandler.cs, src/app/ApplicationTemplate.Client/Framework/HttpDebugger/HttpDebuggerService.cs, src/app/ApplicationTemplate.Client/Framework/HttpDebugger/HttpTrace.cs, src/app/ApplicationTemplate.Client/Framework/HttpDebugger/IHttpDebuggerService.cs, src/app/ApplicationTemplate.Presentation/Configuration/ApiConfiguration.cs, src/app/ApplicationTemplate.Presentation/Configuration/DiagnosticsConfiguration.cs, src/app/ApplicationTemplate.Presentation/Configuration/ViewModelConfiguration.cs, src/app/ApplicationTemplate.Presentation/Framework/ViewModels/IViewModel.Extensions.Options.cs, src/app/ApplicationTemplate.Presentation/Framework/ViewModels/IViewModel.Extensions.PropertyFromDynamicProperty.cs, src/app/ApplicationTemplate.Presentation/Framework/ViewModels/ValueChangedOnBackgroundTaskDynamicPropertyFromDynamicProperty.cs, src/app/ApplicationTemplate.Presentation/ViewModels/Diagnostics/DiagnosticsOverlayViewModel.cs, src/app/ApplicationTemplate.Presentation/ViewModels/Diagnostics/HttpDebugger/HttpDebuggerViewModel.cs, src/app/ApplicationTemplate.Presentation/ViewModels/Diagnostics/HttpDebugger/HttpTraceItemViewModel.cs, src/app/ApplicationTemplate.UWP/ApplicationTemplate.UWP.csproj, src/app/ApplicationTemplate.UWP/Views/Content/Diagnostics/DiagnosticsOverlay.xaml, src/app/ApplicationTemplate.UWP/Views/Content/Diagnostics/HttpDebuggerView.xaml, src/app/ApplicationTemplate.UWP/Views/Content/Diagnostics/HttpDebuggerView.xaml.cs, src/app/ApplicationTemplate.UWP/Views/Styles/Application/Converters.xaml
- Feature
Add HttpDebugger to diagnostics tools.
- Shows all http calls and their status.
- Shows details of selected call, including headers and content for both the request and the response.
- Allows to hide or show headers in the details view, this preference is saved in the diagnostics configuration override.
- Allows to format content (indent json) in the details view, this preference is saved in the diagnostics configuration override.
- Details view allow for text selection (e.g. if you want to copy some content to clipboard).
=> feat: Add HttpTracer.

.azure-pipelines.yml, build/canary-merge.yml, src/app/ApplicationTemplate.Droid/ApplicationTemplate.Droid.csproj, src/app/ApplicationTemplate.UWP/ApplicationTemplate.UWP.csproj, src/app/ApplicationTemplate.UWP/Views/Content/DadJokes/DadJokesFavoritesPage.xaml, src/app/ApplicationTemplate.UWP/Views/Content/DadJokes/DadJokesPage.xaml, src/app/ApplicationTemplate.UWP/Views/Content/DadJokes/DadJokesSearchPage.xaml, src/app/ApplicationTemplate.UWP/Views/Content/Diagnostics/HttpDebuggerView.xaml, src/app/ApplicationTemplate.UWP/Views/Content/Posts/PostsPage.xaml, src/app/ApplicationTemplate.iOS/ApplicationTemplate.iOS.csproj
- Bugfix
- Update Nventive.View and remove workaround for Android `SwipeRefresh`.
- Update the `HttpDebuggerView` to use a monospaced font that actually exists on Android.
- Update pipeline parameters following the `master` to `main` branch rename.
=> Remove SwipeRefresh workaround

.azure-pipelines.yml, .mergify.yml, CONTRIBUTING.md, gitversion.yml
- Chore
chore: Replace master references
=> chore: Replace master references

src/app/ApplicationTemplate.Client/ApplicationTemplate.Client.csproj, src/app/ApplicationTemplate.Droid/ApplicationTemplate.Droid.csproj, src/app/ApplicationTemplate.Presentation/ApplicationTemplate.Presentation.csproj, src/app/ApplicationTemplate.UWP/ApplicationTemplate.UWP.csproj, src/app/ApplicationTemplate.iOS/ApplicationTemplate.iOS.csproj
=> Update chinook and nventive packages

src/ApplicationTemplate.sln
Makes the solution cleaner.
I also noticed that the UI test is currently failing due to an exception.
Before:
After:
=> style: Tests folder in solution.

README.md
Commands are deprecated, updated it to use latest dotnet 7 commands
=> docs: updated readme to include dotnet7 commands

build/stage-build.yml, build/steps-build.yml
Fix building app in pipeline by commenting android and ios builds (non-existent heads)
=> refactor: fix pipeline build

src/app/ApplicationTemplate.Droid/ApplicationTemplate.Droid.csproj, src/app/ApplicationTemplate.Presentation/ApplicationTemplate.Presentation.csproj, src/app/ApplicationTemplate.UWP/ApplicationTemplate.UWP.csproj, src/app/ApplicationTemplate.iOS/ApplicationTemplate.iOS.csproj
- Bugfix
Using the back button would break all binding.
Updating the navigation packages to 1.1.2 fixes this issue.
=> chore: Update dynamicmvvm, backbuttonmanager and sectionsNavigation

src/app/ApplicationTemplate.Mobile/iOS/LaunchScreen.storyboard
- Bugfix
iOS Native Splash Screen was a little bit crushed.
=> fix: iOS Native Splash Screen.

src/app/ApplicationTemplate.Business/ApplicationTemplate.Business.csproj, src/app/ApplicationTemplate.Client/ApplicationTemplate.Client.csproj, src/app/ApplicationTemplate.Mobile/Android/AndroidManifest.xml, src/app/ApplicationTemplate.Mobile/ApplicationTemplate.Mobile.csproj, src/app/ApplicationTemplate.Presentation/ApplicationTemplate.Presentation.csproj, src/app/ApplicationTemplate.Presentation/Configuration/ApiConfiguration.cs, src/app/ApplicationTemplate.Presentation/Configuration/AppServicesConfiguration.cs, src/app/ApplicationTemplate.Presentation/Framework/Connectivity/ConnectivityChangedEventArgs.cs, src/app/ApplicationTemplate.Presentation/Framework/Connectivity/IConnectivity.cs, src/app/ApplicationTemplate.Presentation/Framework/Connectivity/IConnectivityProvider.cs, src/app/ApplicationTemplate.Presentation/Framework/Connectivity/NetworkAccess.cs, src/app/ApplicationTemplate.Presentation/Framework/DataLoader/NetworkReconnectionDataLoaderTrigger.cs, src/app/ApplicationTemplate.Presentation/ViewModels/DadJokes/DadJokesPageViewModel.cs, src/app/ApplicationTemplate.Presentation/ViewModels/Diagnostics/SummaryDiagnosticsViewModel.cs, src/app/ApplicationTemplate.Presentation/ViewModels/Settings/SettingsPageViewModel.cs, src/app/ApplicationTemplate.Shared.Views/App.xaml, src/app/ApplicationTemplate.Shared.Views/ApplicationTemplate.Shared.Views.projitems, src/app/ApplicationTemplate.Shared.Views/Configuration/ApiConfiguration.cs, src/app/ApplicationTemplate.Shared.Views/Configuration/NavigationConfiguration.cs, src/app/ApplicationTemplate.Shared.Views/Configuration/ViewServicesConfiguration.cs, src/app/ApplicationTemplate.Shared.Views/Content/DadJokes/DadJokesPage.xaml.cs, src/app/ApplicationTemplate.Shared.Views/Framework/Connectivity/Connectivity.cs, src/app/ApplicationTemplate.Shared.Views/Framework/Connectivity/ConnectivityProvider.cs, src/app/ApplicationTemplate.Shared.Views/Startup.cs, src/app/ApplicationTemplate.Tests/ApplicationTemplate.Tests.csproj, src/app/ApplicationTemplate.UITests/ApplicationTemplate.UITests.csproj, src/app/ApplicationTemplate.Windows/ApplicationTemplate.Windows.csproj
- Feature
Added Dad Jokes page.
Replaced Xamarin Essentials Connectivity by an Uno implementation.
Enabled some API configuration.
=> feat: Http handlers & Dad Jokes

src/app/ApplicationTemplate.Mobile/Android/AndroidManifest.xml, src/app/ApplicationTemplate.Mobile/Android/LinkerExclusions.xml, src/app/ApplicationTemplate.Mobile/Android/Resources/xml/files.xml, src/app/ApplicationTemplate.Mobile/Android/Resources/xml/network_security_config.xml, src/app/ApplicationTemplate.Mobile/Android/Resources/xml/network_security_config_prod.xml, src/app/ApplicationTemplate.Mobile/ApplicationTemplate.Mobile.csproj, src/app/ApplicationTemplate.Mobile/iOS/LinkerExclusions.xml
- Bugfix
- Feature
Added missing configuration and removed lines from linker exclusion that were causing warnings.
=> feat: network security config

.azure-pipelines-canary.yml, .azure-pipelines.yml, build/stage-release-appcenter.yml, build/variables.yml
- Bugfix
chore: remove uwp app center release
=> chore: remove uwp app center release

src/app/ApplicationTemplate.Mobile/iOS/LinkerExclusions.xml, src/app/ApplicationTemplate.Presentation/ViewModels/Authentication/CreateAccountFormViewModel.cs, src/app/ApplicationTemplate.Shared.Views/Behaviors/FormattingTextBoxBehavior.Android.cs, src/app/ApplicationTemplate.Shared.Views/Configuration/LocalizationConfiguration.cs, src/app/ApplicationTemplate.Shared.Views/Helpers/ObservableExtensions.cs
Removed warnings and clean code a little bit.
=> chore: remove warnings and clean

src/app/ApplicationTemplate.Shared.Views/ApplicationTemplate.Shared.Views.projitems, src/app/ApplicationTemplate.Shared.Views/Configuration/NavigationConfiguration.cs, src/app/ApplicationTemplate.Shared.Views/Content/DadJokes/DadJokesFiltersPage.xaml.cs, src/app/ApplicationTemplate.Shared.Views/Content/Settings/EditProfilePage.xaml.cs, src/app/ApplicationTemplate.Shared.Views/Content/Settings/LicensesPage.xaml.cs
- Feature
Add remaining pages.
=> feat: Add remaining pages

src/app/ApplicationTemplate.Mobile/iOS/Entitlements.plist
- Bugfix
Fixed iOS simulator persistence issue.
=> fix: iOS simulator persistence

src/app/ApplicationTemplate.Client/ApplicationTemplate.Client.csproj, src/app/ApplicationTemplate.Mobile/ApplicationTemplate.Mobile.csproj, src/app/ApplicationTemplate.Shared.Views/Startup.cs, src/app/ApplicationTemplate.Windows/ApplicationTemplate.Windows.csproj
- Feature
Update persistence packages.
Bring back button manager.
=> feat: back button manager

build/steps-build-ios.yml, src/app/ApplicationTemplate.Mobile/Android/AndroidManifest.xml, src/app/ApplicationTemplate.Mobile/iOS/Info.plist, src/app/ApplicationTemplate.Presentation/Framework/Version/IVersionProvider.cs, src/app/ApplicationTemplate.Presentation/Framework/Version/VersionProviderExtensions.cs, src/app/ApplicationTemplate.Presentation/ViewModels/Settings/SettingsPageViewModel.cs, src/app/ApplicationTemplate.Shared.Views/ApplicationTemplate.Shared.Views.projitems, src/app/ApplicationTemplate.Shared.Views/Framework/Version/VersionProvider.Mobile.cs, src/app/ApplicationTemplate.Shared.Views/Framework/Version/VersionProvider.Windows.cs, src/app/ApplicationTemplate.Shared.Views/Framework/Version/VersionProvider.cs
- Bugfix
Using MAUI Essentials for application version until Uno fixes the implementation.
Issue: https://github.com/unoplatform/uno/issues/11216
=> fix: App Version

src/app/ApplicationTemplate.Presentation/Framework/Version/VersionProviderExtensions.cs
=> fix: Version extension

src/app/ApplicationTemplate.Mobile/ApplicationTemplate.Mobile.csproj
- Bugfix
Disable linker on release builds so that Refit and Deserialization work.
It's not clear how to properly set it up with exclusions (what we tried doesn't work).
https://github.com/unoplatform/uno/issues/11248
=> Disable linker

src/app/ApplicationTemplate.Shared.Views/App.xaml.cs, src/app/ApplicationTemplate.Shared.Views/ApplicationTemplate.Shared.Views.projitems, src/app/ApplicationTemplate.Shared.Views/Content/Settings/EditProfilePage.xaml.cs, src/app/ApplicationTemplate.Shared.Views/Content/Settings/SettingsPage.xaml, src/app/ApplicationTemplate.Shared.Views/Controls/AppBarBackButton.cs, src/app/ApplicationTemplate.Shared.Views/Converters/FromNullableAppBarButtonToAppBarButtonConverter.cs, src/app/ApplicationTemplate.Shared.Views/Styles/Application/Converters.xaml, src/app/ApplicationTemplate.Shared.Views/Styles/Controls/CommandBar.xaml, src/app/ApplicationTemplate.Shared.Views/Styles/Controls/Frame.xaml
- Bugfix
- Feature
Add back button for Windows
=> feat: Windows Back Button

src/app/ApplicationTemplate.Mobile/Android/AndroidManifest.xml
- Bugfix
Fix Android release build on AppCenter.
=> fix: Android Internet

src/app/ApplicationTemplate.Tests/Business/PostServiceShould.Mock.cs, src/app/ApplicationTemplate.Tests/Business/PostServiceShould.cs, src/app/ApplicationTemplate.Tests/Business/UserProfileServiceShould.Mock.cs, src/app/ApplicationTemplate.Tests/Business/UserProfileServiceShould.cs, src/app/ApplicationTemplate.Tests/Client/DadJokesEndpointShould.cs, src/app/ApplicationTemplate.Tests/Client/PostEndpointShould.cs, src/app/ApplicationTemplate.Tests/Presentation/DadJokesFilterPageViewModelShould.cs, src/app/ApplicationTemplate.Tests/Presentation/NavigationShould.cs, src/app/ApplicationTemplate.Tests/Presentation/NavigationTestsBase.cs, src/app/ApplicationTemplate.Tests/Presentation/PostsPageViewModelShould.cs
=> Merge unit tests onto feature/dotnet-6 branch

src/app/ApplicationTemplate.Mobile/Android/MainActivity.Android.cs
- Bugfix
- Feature
https://github.com/unoplatform/uno/issues/11300
=> fix: Android Default Soft Input

build/variables.yml
- Bugfix
https://teams.microsoft.com/l/message/19:11f38c6ef6754652ab82a0141e78b214@thread.tacv2/1675981873795?tenantId=6d53ef61-b6d1-4150-ae0b-43b90e75e0cd&groupId=811f2298-2d05-4634-a2d5-e81c9ae21406&parentMessageId=1675981873795&teamName=Developers&channelName=Mobile%20.net-Uno&createdTime=1675981873795&allowXTenantAccess=false
=> fix: new pipeline

src/app/ApplicationTemplate.Presentation/CoreStartup.cs, src/app/ApplicationTemplate.Presentation/ViewModels/Diagnostics/Navigation/NavigationDebuggerViewModel.cs, src/app/ApplicationTemplate.Shared.Views/ApplicationTemplate.Shared.Views.projitems, src/app/ApplicationTemplate.Shared.Views/Content/Diagnostics/DiagnosticsTabPresenter.cs, src/app/ApplicationTemplate.Shared.Views/Content/Diagnostics/NavigationDebuggerView.xaml, src/app/ApplicationTemplate.Shared.Views/Content/Diagnostics/NavigationDebuggerView.xaml.cs
- Feature
Add buttons to clear and restore navigation to help debug various scenarios.
https://user-images.githubusercontent.com/39710855/225053965-0b337ee9-e965-4623-be21-14b5f20e66b3.MP4
=> feat: Add diagnostics buttons to clear and restore navigation.

src/app/ApplicationTemplate.Mobile/Android/MainActivity.Android.cs, src/app/ApplicationTemplate.Shared.Views/Styles/Controls/CommandBar.xaml
- Bugfix
We noticed in other that we needed this line of code for WinUI command bar. Didn't need it here but now it should work for other people when creating a new app.
=> fix: Command bar

src/app/ApplicationTemplate.Presentation/Configuration/ApiConfiguration.cs, src/app/ApplicationTemplate.Presentation/Framework/DataLoader/NetworkReconnectionDataLoaderTrigger.cs, src/app/ApplicationTemplate.Shared.Views/Framework/Connectivity/ConnectivityProvider.cs
- Bugfix
Noticed forgotten things from the migration and also noticed a bug on Windows in a project migration.
=> fix: Connectivity

src/app/ApplicationTemplate.Shared.Views/App.xaml
- Feature
Improve Uno Material initialization after implementing V2
[Product Backlog Item 281257](https://dev.azure.com/nventive/Practice%20committees/_workitems/edit/281257): Upgrade UnoApplicationTemplate to Uno.Material V2
=> feat(281257): improve Uno Material initialization

src/app/ApplicationTemplate.Presentation/ViewModels/Diagnostics/Configuration/ConfigurationDebuggerViewModel.cs, src/app/ApplicationTemplate.Presentation/ViewModels/Diagnostics/DiagnosticsOverlayViewModel.cs, src/app/ApplicationTemplate.Shared.Views/ApplicationTemplate.Shared.Views.projitems, src/app/ApplicationTemplate.Shared.Views/Content/Diagnostics/ConfigurationDebuggerView.xaml, src/app/ApplicationTemplate.Shared.Views/Content/Diagnostics/ConfigurationDebuggerView.xaml.cs, src/app/ApplicationTemplate.Shared.Views/Content/Diagnostics/DiagnosticsTabPresenter.cs
- Feature
- Add a Configuration tab in the expanded diagnostics overlay.
- It currently displays the current `IConfiguration` as Json.
- It's automatically refreshed when the configuration changes.
=> feat: Add ConfigurationDebuggerView in the diagnostics overlay.

doc/PlatformSpecifics.md, src/app/ApplicationTemplate.Client/ApplicationTemplate.Client.csproj, src/app/ApplicationTemplate.Mobile/Android/AndroidManifest.xml, src/app/ApplicationTemplate.Mobile/ApplicationTemplate.Mobile.csproj, src/app/ApplicationTemplate.Windows/ApplicationTemplate.Windows.csproj
=> Add Target for net7

build/canary-merge.yml, build/stage-build.yml, build/stage-release-appcenter.yml, build/steps-build-android.yml, build/steps-build-ios.yml, build/steps-build-windows.yml, build/templates/dotnet-install.yml
=> Update variable to target net7

src/app/ApplicationTemplate.Presentation/ViewModels/MenuViewModel.cs, src/app/ApplicationTemplate.Shared.Views/Content/Menu.xaml
- Bugfix
Fixed comments [here](https://github.com/nventive/UnoApplicationTemplate/pull/302).
Removed `TwoWay` binding since it's an Uno.Toolkit.UI [bug](https://github.com/unoplatform/uno.toolkit.ui/issues/562) on Windows.
=> fix: Menu VM

doc/Environments.md, src/app/ApplicationTemplate.Presentation/Configuration/ConfigurationConfiguration.cs, src/app/ApplicationTemplate.Presentation/Configuration/EnvironmentManager.cs, src/app/ApplicationTemplate.Presentation/Configuration/IEnvironmentManager.cs, src/app/ApplicationTemplate.Presentation/CoreStartup.cs, src/app/ApplicationTemplate.Presentation/Framework/Startup/CoreStartupBase.cs, src/app/ApplicationTemplate.Presentation/Framework/Startup/StartupBase.cs, src/app/ApplicationTemplate.Presentation/ViewModels/Diagnostics/DiagnosticsPageViewModel.cs, src/app/ApplicationTemplate.Presentation/ViewModels/Diagnostics/EnvironmentPickerPageViewModel.cs, src/app/ApplicationTemplate.Presentation/ViewModels/Diagnostics/SummaryDiagnosticsViewModel.cs, src/app/ApplicationTemplate.Shared.Views/App.xaml.cs, src/app/ApplicationTemplate.Tests/Framework/IntegrationTestBase.cs, src/app/ApplicationTemplate.Tests/Framework/TestEnvironmentManager.cs
- Refactoring (no functional changes, ~~no api changes~~)
- Replace `AppEnvironment` (static class) by `IEnvironmentManager`.
- Using an interface allows for multiple implementations, including one that doesn't do any I/O for tests, which improves their performance.
- Rename `AppSettings` to `AppSettingsFile` for clarity.
=> feat: Replace AppEnvironment by IEnvironmentManager

src/app/ApplicationTemplate.Presentation/ApplicationTemplate.Presentation.csproj, src/app/ApplicationTemplate.Presentation/Framework/Memory/IMemoryProvider.cs, src/app/ApplicationTemplate.Presentation/ViewModels/Diagnostics/DiagnosticsOverlayViewModel.cs, src/app/ApplicationTemplate.Shared.Views/ApplicationTemplate.Shared.Views.projitems, src/app/ApplicationTemplate.Shared.Views/Configuration/ViewServicesConfiguration.cs, src/app/ApplicationTemplate.Shared.Views/Content/Diagnostics/DiagnosticsOverlay.xaml, src/app/ApplicationTemplate.Shared.Views/Framework/Memory/MemoryProvider.cs, src/app/ApplicationTemplate.Shared.Views/Framework/Memory/MemoryProvider.iOS.cs
- Feature
Added Private Memory allocated to the app (1)
Added total memory managed memory to the app (2)
=> feat: Track private memory allocated

CHANGELOG.md, src/app/ApplicationTemplate.Mobile/Android/AndroidManifest.xml
This PR allows the app to support Android 13.
- Feature
2 files have been modified: AndroidManifest.xml and the CHANGELOG. The app now supports Android SDK 33 (which is Android 13).
=> feat: update to support Android 13

.azure-pipelines-canary.yml, .azure-pipelines.yml, build/stage-build.yml, build/stage-release-appstore.yml, build/steps-build-ios.yml
- Feature
Add TestFlight Flow.
App center is still used, but with the limitation of individual account
=> Add TestFlight Flow

README.md
GitHub Issue: #325 
- Bugfix
- Feature
I just added a mention that periods in project name aren't supported
=> feat: Add unsupported mentions in the readme

src/app/ApplicationTemplate.Presentation/ViewModels/Diagnostics/DiagnosticsPageViewModel.cs, src/app/ApplicationTemplate.Presentation/ViewModels/StarRating/StarRatingTestingPageViewModel.cs, src/app/ApplicationTemplate.Presentation/appsettings.development.json, src/app/ApplicationTemplate.Shared.Views/ApplicationTemplate.Shared.Views.projitems, src/app/ApplicationTemplate.Shared.Views/Configuration/NavigationConfiguration.cs, src/app/ApplicationTemplate.Shared.Views/Content/Diagnostics/DiagnosticsPage.xaml, src/app/ApplicationTemplate.Shared.Views/Content/StarRating/StarRatingTestingPage.xaml, src/app/ApplicationTemplate.Shared.Views/Content/StarRating/StarRatingTestingPage.xaml.cs, src/app/ReviewService.Abstractions/IReviewPrompter.cs, src/app/ReviewService/ReviewPrompter.Android.cs, src/app/ReviewService/ReviewPrompter.Windows.cs, src/app/ReviewService/ReviewPrompter.iOS.cs
- Bugfix
In this pr, I implemented the new star rating interface for NativePrompting. On windows it's only logs, ios and android have native star ratings. 
=> feat: Implement the native prompt service

src/app/ApplicationTemplate.Client/Configuration/PersistenceConfiguration.cs, src/app/ApplicationTemplate.Client/LocalStorage/ReviewConditionCustom.cs, src/app/ApplicationTemplate.Client/LocalStorage/ReviewSettingsCustom.cs, src/app/ApplicationTemplate.Client/LocalStorage/ReviewSettingsSource.cs, src/app/ApplicationTemplate.Presentation/Configuration/AppServicesConfiguration.cs, src/app/ApplicationTemplate.Presentation/ViewModels/Diagnostics/DiagnosticsPageViewModel.cs, src/app/ApplicationTemplate.Presentation/ViewModels/StarRating/ReviewService.Extensions.cs, src/app/ApplicationTemplate.Presentation/ViewModels/StarRating/StarRatingTestingPageViewModel.cs, src/app/ApplicationTemplate.Presentation/ViewModels/Welcome/OnboardingPageViewModel.cs, src/app/ApplicationTemplate.Shared.Views/Configuration/NavigationConfiguration.cs, src/app/ApplicationTemplate.Shared.Views/Configuration/ViewServicesConfiguration.cs, src/app/ApplicationTemplate.Shared.Views/Content/StarRating/StarRatingTestingPage.xaml, src/app/ReviewService.Abstractions/ReviewService.Extensions.cs, src/app/ReviewService/ReviewService.cs
- Bugfix
I implemented the conditions service into the app template
=> feat: Implement the conditions and triggers service

README.md, doc/Logging.md, doc/Reviews.md, src/app/ApplicationTemplate.Client/ApplicationTemplate.Client.csproj, src/app/ApplicationTemplate.Client/Configuration/PersistenceConfiguration.cs, src/app/ApplicationTemplate.Client/LocalStorage/DataPersisterReviewSettingsSource.cs, src/app/ApplicationTemplate.Mobile/ApplicationTemplate.Mobile.csproj, src/app/ApplicationTemplate.Presentation/ApplicationTemplate.Presentation.csproj, src/app/ApplicationTemplate.Presentation/Configuration/ApiConfiguration.cs, src/app/ApplicationTemplate.Presentation/Configuration/ReviewConfiguration.cs, src/app/ApplicationTemplate.Presentation/CoreStartup.cs, src/app/ApplicationTemplate.Presentation/ViewModels/DadJokes/DadJokesPageViewModel.cs, src/app/ApplicationTemplate.Presentation/ViewModels/MenuViewModel.cs, src/app/ApplicationTemplate.Shared.Views/Configuration/PersistenceConfiguration.cs, src/app/ApplicationTemplate.Shared.Views/Configuration/ViewServicesConfiguration.cs, src/app/ApplicationTemplate.Windows/ApplicationTemplate.Windows.csproj
- Bugfix
- Feature
- Fix dad jokes not loading on WinUI.
- Add ReviewService.
=> feat: Add ReviewService

src/app/ApplicationTemplate.Client/ApplicationTemplate.Client.csproj, src/app/ApplicationTemplate.Mobile/ApplicationTemplate.Mobile.csproj, src/app/ApplicationTemplate.Presentation/ApplicationTemplate.Presentation.csproj, src/app/ApplicationTemplate.Windows/ApplicationTemplate.Windows.csproj
- Feature
- Update ReviewService packages to the stable version.
=> chore: Update ReviewService packages to the stable version.

src/app/ApplicationTemplate.Mobile/ApplicationTemplate.Mobile.csproj, src/app/ApplicationTemplate.Presentation/ApplicationTemplate.Presentation.csproj, src/app/ApplicationTemplate.Windows/ApplicationTemplate.Windows.csproj
- Other... Please describe: chore
chore: consolidate package versions
=> chore: consolidate package versions

src/app/ApplicationTemplate.Mobile/Android/AndroidManifest.xml, src/app/ApplicationTemplate.Mobile/ApplicationTemplate.Mobile.csproj
- Bugfix
- Feature
feat: update min sdk version of Android to sdk 29 (Android 10)
=> Update min sdk version of Android

src/app/ApplicationTemplate.Client/Configuration/SerializationConfiguration.cs, src/app/ApplicationTemplate.Presentation/ViewModels/Diagnostics/Configuration/ConfigurationDebuggerViewModel.cs, src/app/ApplicationTemplate.Shared.Views/Content/Diagnostics/ConfigurationDebuggerView.xaml
- Feature
Add basic controls to enable editing the configuration.
=> feat: Add a basic configuration editor in the ConfigurationDebugger.

src/app/ApplicationTemplate.Client/Configuration/SerializationConfiguration.cs, src/app/ApplicationTemplate.Shared.Views/Configuration/PersistenceConfiguration.cs
- Bugfix
Fix issue where deserialization of ReviewSettings would throw exceptions because of missing metadata.
This was resolved by using reflection-based deserialization (instead of source-generation-based deserialization).
=> fix: Resolve deserialization issue around ReviewService.

.github/PULL_REQUEST_TEMPLATE.md, .template.config/build/gitversion-config.yml, CHANGELOG.md, README.md
* Updated installation documentation.
* Update GitHub PR template to include checks around versioning.
Based on your changes these checks may not apply.
=> docs: Update readme and PR template.

.template.config/template.json, CHANGELOG.md
Fixed usage of guids to prevent having conflicts with generating multiple projects with the template.
Based on your changes these checks may not apply.
=> fix: Use proper guids in template configuration.

.azuredevops/pull_request_template.md, .github/PULL_REQUEST_TEMPLATE.md, APP_README.md, CHANGELOG.md, README.md, doc/Architecture.md, doc/Diagnostics.md, doc/HTTP.md, doc/Localization.md, doc/Logging.md, doc/Mvvm.md, doc/Navigation.md, doc/Startup.md
* Improved architecture documentation by adding a **Technical Overview** section listing all major recipes.
- Update `Diagnostics.md` if you made …
=> docs: Add more structure to architecture documentation.

CHANGELOG.md, src/app/ApplicationTemplate.Mobile/iOS/Info.plist
Removed deprecated info.plist keys.
- Update `Architecture.md` and its diagrams …
=> chore: remove deprecated info.plist keys

build/templates/gitversion.yml, build/variables.yml
Updated the macos pool to 2023 and updated git version
- Update …
=> ci: updated the macos pool

build/canary-merge.yml, build/steps-build-android.yml
fix canary merge by consolidating the usage of variables yml
- Update …
=> fix: fix canary merge by using variables yml

CHANGELOG.md, doc/Architecture.md, doc/DefaultAnalytics.md, src/app/ApplicationTemplate.Presentation/Configuration/AnalyticsConfiguration.cs, src/app/ApplicationTemplate.Presentation/Configuration/ViewModelConfiguration.cs, src/app/ApplicationTemplate.Presentation/CoreStartup.cs, src/app/ApplicationTemplate.Presentation/Framework/Analytics/AnalytcsSink.cs, src/app/ApplicationTemplate.Presentation/Framework/Analytics/AnalyticsCommandStrategy.cs, src/app/ApplicationTemplate.Presentation/Framework/Analytics/IAnalyticsSink.cs, src/app/ApplicationTemplate.Presentation/Framework/DataLoader/MonitoringDataLoaderStrategy.cs, src/app/ApplicationTemplate.Presentation/ViewModels/Extensions/SectionsNavigatorState.Extensions.cs, src/app/ApplicationTemplate.Presentation/ViewModels/MenuViewModel.cs, src/app/ApplicationTemplate.Shared.Views/Startup.cs
- Added hooks for default analytics (page views, and command invocations).
- …
=> feat: Add default analytics hooks.

.azure-pipelines-api-integration-tests.yml, CHANGELOG.md, build/stage-release-appcenter.yml, build/stage-release-appstore.yml, build/variables.yml, doc/Architecture.md, doc/DefaultAnalytics.md, src/app/ApplicationTemplate.Presentation/Configuration/AnalyticsConfiguration.cs, src/app/ApplicationTemplate.Presentation/Configuration/ViewModelConfiguration.cs, src/app/ApplicationTemplate.Presentation/CoreStartup.cs, src/app/ApplicationTemplate.Presentation/Framework/Analytics/AnalytcsSink.cs, src/app/ApplicationTemplate.Presentation/Framework/Analytics/AnalyticsCommandStrategy.cs, src/app/ApplicationTemplate.Presentation/Framework/Analytics/IAnalyticsSink.cs, src/app/ApplicationTemplate.Presentation/Framework/DataLoader/MonitoringDataLoaderStrategy.cs, src/app/ApplicationTemplate.Presentation/ViewModels/Extensions/SectionsNavigatorState.Extensions.cs, src/app/ApplicationTemplate.Presentation/ViewModels/MenuViewModel.cs, src/app/ApplicationTemplate.Shared.Views/Startup.cs
Merge main in feature/uno5
- Update `Architecture.md` and its diagrams if you …
=> Merge main in feature/uno5

CHANGELOG.md, build/templates/dotnet-install.yml, src/app/ApplicationTemplate.Access/ApplicationTemplate.Access.csproj, src/app/ApplicationTemplate.Mobile/ApplicationTemplate.Mobile.csproj, src/app/ApplicationTemplate.Presentation/ApplicationTemplate.Presentation.csproj, src/app/ApplicationTemplate.Shared.Views/App.xaml.cs, src/app/ApplicationTemplate.Windows/ApplicationTemplate.Windows.csproj, src/app/ApplicationTemplate.Windows/Package.appxmanifest
Update to Uno 5
- Update `Architecture.md` and its diagrams if you made …
=> feat!: update to uno 5

.azure-pipelines-api-integration-tests.yml, CHANGELOG.md
I've adjusted the cron schedule expression under the integration test api CI so it does run this CI every day of the week.
- Update `Diagnostics.md` …
=> fix: adjust api integration test ci cron to run everyday of the week

CHANGELOG.md, build/canary-merge.yml, build/templates/dotnet-install.yml, build/variables.yml
fix canary builds
refactor dotnet version number
- Update `Architecture.md` and …
=> Fix canary builds

CHANGELOG.md, build/canary-merge.yml
… merge
I'm setting `fetchDepth` to `0` on the canary-merge CI under the checkout task to avoid `refusing to merge unrelated histories` errors
- …
=> fix: set fetchDepth to 0

APP_README.md, CHANGELOG.md, build/variables.yml
Update macOS MS-Hosted agents to macOS 13 (Ventura) so that we build with iOS 17
- Update `Diagnostics.md` if you made changes to **diagnostic …
=> ci: Update macOS MS-Hosted agents to macOS 13

src/app/ApplicationTemplate.Presentation/CoreStartup.cs
Remove the killswitch from the stack before you go back to normal navigation. You will otherwise get stuck there again if you change to the section with the kill switch page
- Update `AzurePipelines.md` and `APP_README.md` if you made …
=> fix: kill switch page remaining

CHANGELOG.md, src/app/ApplicationTemplate.Shared.Views/Configuration/LoggingConfiguration.cs
The issue is that when the app is built with the loggers set to false in the appsettings.json serilog doesn't create the directory that hosts the appsettings.override.json file so it causes all sorts of issue with localization and enabling loggers in the diagnostics because the directory doesn't exist. So we create it manually whenever the loggers are disabled to prevent this.
- If you create a new header, it aligns with the **Impact on version** …
=> fix: Cannot activate file logging

CHANGELOG.md, src/app/ApplicationTemplate.Access/ApplicationTemplate.Access.csproj
- Update System.Text.Json to resolve security issue.
- Update `Architecture.md` …
=> fix: Update System.Text.Json to resolve security issue.

CHANGELOG.md, doc/Diagnostics.md
I removed UWP reference in diagnostics.md. …
=> docs: fix typo in diagnostics.md

src/app/ApplicationTemplate.Access/ApplicationTemplate.Access.csproj
- Resolve [security advisory CVE-2024-43485](https://github.com/advisories/GHSA-8g4q-xg66-9fp4).
- Update `Diagnostics.md` if you made changes to …
=> fix: Resolve security advisory CVE-2024-43485.

CHANGELOG.md, src/app/ApplicationTemplate.Mobile/ApplicationTemplate.Mobile.csproj
Without the added runtime identifiers the app cannot build on my android device because the cpu is not supported by the projects.
- Update …
=> fix: Adding support for arm64, x86 cpus for android

CHANGELOG.md, doc/PlatformSpecifics.md, src/app/ApplicationTemplate.Access/ApplicationTemplate.Access.csproj, src/app/ApplicationTemplate.Mobile/ApplicationTemplate.Mobile.csproj, src/app/ApplicationTemplate.Presentation/ApplicationTemplate.Presentation.csproj, src/app/ApplicationTemplate.Shared.Views/Content/Diagnostics/DiagnosticsPage.xaml, src/app/ApplicationTemplate.Tests.Functional/ApplicationTemplate.Tests.Functional.csproj, src/app/ApplicationTemplate.Tests.Functional/FunctionalTestBase.cs, src/app/ApplicationTemplate.Tests.Functional/KillSwitch/KillSwitchShould.cs, src/app/ApplicationTemplate.Tests.Unit/ApplicationTemplate.Tests.Unit.csproj, src/app/ApplicationTemplate.Windows/ApplicationTemplate.Windows.csproj
I fixed the iOS crash by updating most of the application packages and I fixed an issue with the tests (race condition).
- Update `Diagnostics.md` if …
=> fix: iOS Crash

CHANGELOG.md, src/app/ApplicationTemplate.Mobile/ApplicationTemplate.Mobile.csproj, src/app/ApplicationTemplate.Shared.Views/App.xaml.cs, src/app/ApplicationTemplate.Windows/ApplicationTemplate.Windows.csproj
Update Uno packages to the latest version. …
=> chore: Update Uno

build/templates/validate-commits.yaml
- Update `Architecture.md` and its diagrams if you made **architecture …
=> ci: Fix Commits Validator Pattern

CHANGELOG.md, build/templates/validate-commits.yaml, src/app/ApplicationTemplate.Mobile/ApplicationTemplate.Mobile.csproj, src/app/ApplicationTemplate.Shared.Views/App.xaml.cs, src/app/ApplicationTemplate.Shared.Views/ApplicationTemplate.Shared.Views.projitems, src/app/ApplicationTemplate.Shared.Views/Behaviors/CommandBarSafeAreaBehavior.cs, src/app/ApplicationTemplate.Shared.Views/Styles/Controls/CommandBar.xaml, src/app/ApplicationTemplate.Windows/ApplicationTemplate.Windows.csproj
We updated the template to the latest version of Uno.
- Update …
=> feat: Uno Update

.template.config/build/stage-publish-template.yml, CHANGELOG.md, build/canary-merge.yml, build/steps-build-android.yml, build/steps-build-ios.yml, build/steps-build-release-notes.yml, build/steps-build-tests.yml, build/steps-build-windows.yml, build/templates/gitversion.yml, build/variables.yml, src/app/ApplicationTemplate.Windows/ApplicationTemplate.Windows.csproj
ci: update versions
- Update `Architecture.md` and its diagrams if you made …
=> ci: update versions

CHANGELOG.md, src/app/ApplicationTemplate.Access/ApiClients/Authentication/AuthenticationApiClientMock.cs, src/app/ApplicationTemplate.Access/ApiClients/UserProfile/UserProfileRepositoryMock.cs, src/app/ApplicationTemplate.Access/Configuration/MockOptions.cs, src/app/ApplicationTemplate.Presentation/appsettings.json, src/app/ApplicationTemplate.Tests.Functional/FunctionalTestBase.cs
- Added an option parameter to control whether mock implementation should add delays to simulate longer API calls.
- This option is enabled by default for the real app (with UI), but disabled for automated tests. This makes the total duration of the current functional tests go from ~15s to ~500ms.
- Update `README.md` …
=> perf: Improve functional tests performance by disabling delays

doc/Configuration.md
Fixing an issue with the documentation for configurationconfiguration.md
- …
=> docs: Fix the configurationconfiguration documentation

CHANGELOG.md, CONTRIBUTING.md
Adding more information in the contributing.md file
- Update `Architecture.md` …
=> docs: Updated Contributing.md

.azure-pipelines-api-integration-tests.yml, .editorconfig, CHANGELOG.md, build/steps-build-tests.yml, doc/AzurePipelines.md, doc/Testing.md, src/ApplicationTemplate.sln, src/app/ApplicationTemplate.Access/ApiClients/DadJokes/Data/DadJokeContentData.cs, src/app/ApplicationTemplate.Access/ApiClients/DadJokes/IDadJokesApiClient.cs, src/app/ApplicationTemplate.Tests.Api/ApiTestBase.cs, src/app/ApplicationTemplate.Tests.Api/ApplicationTemplate.Tests.Api.csproj, src/app/ApplicationTemplate.Tests.Api/DadJokesApiClientShould.cs, src/app/ApplicationTemplate.Tests.Api/Usings.cs, src/app/ApplicationTemplate.Tests.Functional/ApplicationTemplate.Tests.Functional.csproj, src/app/ApplicationTemplate.Tests.Functional/FunctionalTestBase.Extensions.cs, src/app/ApplicationTemplate.Tests.Functional/FunctionalTestBase.cs, src/app/ApplicationTemplate.Tests.Unit/ApplicationTemplate.Tests.Unit.csproj, src/app/ApplicationTemplate.Tests/ApplicationTemplate.Tests.csproj, src/app/ApplicationTemplate.Tests/TestEnvironmentManager.cs
I added an API tests project to isolate our API integration tests. I've updated the integration tests pipeline and the documentation. I've also done some code cleanup and removed some unused namespaces.
- Update `AzurePipelines.md` and …
=> feat: Add API Client Tests

CHANGELOG.md, src/app/ApplicationTemplate.Mobile/Android/AndroidManifest.xml, src/app/ApplicationTemplate.Mobile/Android/MainActivity.Android.cs
Fixed the weird space at the bottom of the screen.
Before.
After.
- Update …
=> fix: Android Bottom Screen Space
